package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Informacion de la tabla que trae las tasas 
 * en una relacion de uno a muchos (una campaña tiene muchas tasas)
 * a su vez la tasa tiene uno a muchos plazos
 * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * SccMxPrcOferMaxTasa generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_PRC_OFER_MAX_TASA")
public class SccMxPrcOferMaxTasa implements IAbstractEntity, java.io.Serializable {


	/**
	 * serializacion de la entidad SccMxPrcOferMaxTasa
	 */
	private static final long serialVersionUID = 3576912812334635480L;
	/**
	 *llave maestra (indice unico secuencial) de la entidad SccMxPrcOferMaxTasa
	 */
	private Long idOferMaxTasaPk;
	/**
	 * Relacion con la entidad Campanias de la entidad SccMxPrcOferMaxTasa
	 */
	private SccMxMaeOferCam sccMxMaeOferCam;
	/**
	 * Indica el tipo de tasa (BASE, 1, 2, ETC) 
	 */
	private String codTasa;
	/**
	 * Porcentaje anual de la tasa indicada
	 */
	private Double porTasa;

	/**
	 * Constructor vacio
	 */
	public SccMxPrcOferMaxTasa() {
	}

	/**
	 * COnstructor de ofertas maximas por tasa
	 * @param idOferMaxTasaPk
	 * llave
	 * @param sccMxMaeOferCam
	 * conexion con ofertas de campa_a
	 * @param codTasa
	 * codigo de tasa
	 * @param porTasa
	 * porcentaje de tasa
	 */
	public SccMxPrcOferMaxTasa(Long idOferMaxTasaPk, SccMxMaeOferCam sccMxMaeOferCam, String codTasa, Double porTasa) {
		this.idOferMaxTasaPk = idOferMaxTasaPk;
		this.sccMxMaeOferCam = sccMxMaeOferCam;
		this.codTasa = codTasa;
		this.porTasa = porTasa;
	}

	@Id
	@Column(name = "ID_OFER_MAX_TASA_PK", unique = true, nullable = false, precision = 22, scale = 0)
	/**
	 * Getters y setters 
	 * @return idOferMaxTasaPk
	 * Llave principal
	 */
	public Long getIdOferMaxTasaPk() {
		return this.idOferMaxTasaPk;
	}

	/**
	 * Llave principal
	 * @param idOferMaxTasaPk
	 * Obtiene llave principal
	 */
	public void setIdOferMaxTasaPk(Long idOferMaxTasaPk) {
		this.idOferMaxTasaPk = idOferMaxTasaPk;
	}

	/**
	 * @return SccMxMaeOferCam sccMxMaeOferCam Clase de datos de oferta de campaña
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_OFER_CAM_FK", nullable = false)
	public SccMxMaeOferCam getSccMxMaeOferCam() {
		return this.sccMxMaeOferCam;
	}

	/**
	 * @param sccMxMaeOferCam SccMxMaeOferCam Clase de datos de oferta de campaña
	 */
	public void setSccMxMaeOferCam(SccMxMaeOferCam sccMxMaeOferCam) {
		this.sccMxMaeOferCam = sccMxMaeOferCam;
	}

	/**
	 * @return String codTasa Código de tasa
	 */
	@Column(name = "COD_TASA", nullable = false, length = 20)
	public String getCodTasa() {
		return this.codTasa;
	}

	/**
	 * @param codTasa String Código de tasa
	 */
	public void setCodTasa(String codTasa) {
		this.codTasa = codTasa;
	}

	/**
	 * @return Double porTasa Porcentaje de tasa
	 */
	@Column(name = "POR_TASA", nullable = false, precision = 22, scale = 0)
	public Double getPorTasa() {
		return this.porTasa;
	}

	/**
	 * @param porTasa Double Porcentaje de tasa
	 */
	public void setPorTasa(Double porTasa) {
		this.porTasa = porTasa;
	}

}
