package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Clase para manejar la tabla de segmentos
 * catalogo que describe los posibles codigos de segmentos
 * y los relaciona con la tasa de conversion auto correspondiente
 * Los codigos de segmentos por usuario se definen en la tabla de campanias
 * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * Tabla de Segmentos
 * SccMxMaeSegmento generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_SEGMENTO")
public class SccMxMaeSegmento implements IAbstractEntity, java.io.Serializable {


	/**
	 * Seralizador de la clase
	 */
	private static final long serialVersionUID = -3316685141807288129L;
	/**
	 * Llave primaria de segmento
	 */
	private Long idSegmentoPk;
	/**
	 * descripción de segmento
	 */
	private String dscSegmento;
	/**
	 * Codigo de segmento
	 */
	private String codSegmento;
	/**
	 * conv auto en la entidad SccMxMaeSegmento
	 */
	private SccMxMaeConvauto sccMxMaeConvauto;
	
	/**
	 * Constructor Vacio
	 */
	public SccMxMaeSegmento() {
	}

	/**
	 * constructor mini 
	 * @param idSegmentoPk
	 * Llave
	 */
	public SccMxMaeSegmento(Long idSegmentoPk) {
		this.idSegmentoPk = idSegmentoPk;
	}

	/**
	 * Constructor para la tabla maestra de segmento
	 * @param idSegmentoPk
	 * Id de segmento
	 * @param dscSegmento
	 * descripcion de segmento
	 * @param codSegmento
	 * codigo de segmento
	 */
	public SccMxMaeSegmento(Long idSegmentoPk, String dscSegmento, String codSegmento) {
		this.idSegmentoPk = idSegmentoPk;
		this.dscSegmento = dscSegmento;
		this.codSegmento = codSegmento;
	}
	
	/**
	 * @return SccMxMaeConvauto sccMxMaeConvauto Clase de datos de conversión auto
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_CONVAUTO_FK")
	public SccMxMaeConvauto getSccMxMaeConvauto() {
		return sccMxMaeConvauto;
	}

	/**
	 * @param sccMxMaeConvauto SccMxMaeConvauto Clase de datos de conversión auto
	 */
	public void setSccMxMaeConvauto(SccMxMaeConvauto sccMxMaeConvauto) {
		this.sccMxMaeConvauto = sccMxMaeConvauto;
	}


	/**
	 * @return Long idSegmentoPk Id del segmento
	 */
	@Id
	@Column(name = "ID_SEGMENTO_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdSegmentoPk() {
		return this.idSegmentoPk;
	}

	/**
	 * @param idSegmentoPk Long Id del segmento
	 */
	public void setIdSegmentoPk(Long idSegmentoPk) {
		this.idSegmentoPk = idSegmentoPk;
	}

	/**
	 * @return String dscSegmento Nombre del segmento
	 */
	@Column(name = "DSC_SEGMENTO", length = 100)
	public String getDscSegmento() {
		return this.dscSegmento;
	}

	/**
	 * @param dscSegmento String Nombre del segmento
	 */
	public void setDscSegmento(String dscSegmento) {
		this.dscSegmento = dscSegmento;
	}

	/**
	 * @return String codSegmento Código del segmento
	 */
	@Column(name = "COD_SEGMENTO_ORI", length = 100)
	public String getCodSegmento() {
		return this.codSegmento;
	}

	/**
	 * @param codSegmento String Código del segmento
	 */
	public void setCodSegmento(String codSegmento) {
		this.codSegmento = codSegmento;
	}

	
}
