package mx.isban.scc.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Entidad para catalogo de perfiles
  * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * SccMxMaePerfiles generated by hbm2java
 * @author Hitss
 */
@Entity
@Table(name = "SCC_MX_MAE_PERFILES")
public class SccMxMaePerfiles implements IAbstractEntity,java.io.Serializable {

	/**
	 * variable para log
	 */
	private static final long serialVersionUID = -3160917501520413905L;
	@Id
	/**
	 * Llave principal para identificar al perfil
	 */
	private Long idPerfilPk;
	/**
	 * Descripcion del perfil: Red, Sucursal, etc
	 */
	private String dscPerfil;
	/**
	 * Llave foranea con el tipo de usuario: Administrador, consulta, comercial
	 */
	private Long idTipoUsrFk;

	/**
	 * constructor con parametros
	 * 
	 * @param idPerfilPk idPerfil
	 * @param dscPerfil descripcion perfil
	 * @param idTipoUsrFk idTipousr
	 */
	public SccMxMaePerfiles(Long idPerfilPk, String dscPerfil, Long idTipoUsrFk) {
		super();
		this.idPerfilPk = idPerfilPk;
		this.dscPerfil = dscPerfil;
		this.idTipoUsrFk = idTipoUsrFk;
	}

	/**
	 * constructor por defecto
	 * sin parámetros
	 */
	public SccMxMaePerfiles() {
	}

	/**
	 * @return Long idPerfilPk Id de perfil 
	 */
	public Long getIdPerfilPk() {
		return idPerfilPk;
	}

	/**
	 * @param idPerfilPk Long Id de perfil
	 */
	public void setIdPerfilPk(Long idPerfilPk) {
		this.idPerfilPk = idPerfilPk;
	}

	/**
	 * @return String dscPerfil Nombre de perfil
	 */
	public String getDscPerfil() {
		return dscPerfil;
	}

	/**
	 * @param dscPerfil String Nombre de perfil
	 */
	public void setDscPerfil(String dscPerfil) {
		this.dscPerfil = dscPerfil;
	}

	/**
	 * @return idTipoUsrFk Long Id de tipo usuario
	 */
	public Long getIdTipoUsrFk() {
		return idTipoUsrFk;
	}

	/**
	 * @param idTipoUsrFk Long Id de tipo usuario
	 */
	public void setIdTipoUsrFk(Long idTipoUsrFk) {
		this.idTipoUsrFk = idTipoUsrFk;
	}

}
