package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Catalogo del tipo de producto
 * El usuario puede modificarlo con la interfaz
 * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * Tabla para los tipos de productos
 * SccMxMaeTipoProd generated by hbm2java
 * @author Hitss
 */
@Entity
@Table(name = "SCC_MX_MAE_TIPO_PROD")
public class SccMxMaeTipoProd implements IAbstractEntity, java.io.Serializable {

	
	/**
	 * Identificador para serializar la clase
	 */
	private static final long serialVersionUID = -6349739340621886696L;
	/**
	 * LLave primaria tipo de producto
	 */
	private Long idTipoProductoPk;
	/**
	 * Descripción de tipo de producto
	 */
	private String dscTipoProducto;

	/**
	 * Identificador del Grupo de Consumo: Adqui, Resti o Susti
	 */
	private Long idAgrupadoConsumoFk;

	/**
	 * Identificador de la Modalidad: 0= Ninguna, 1=Campaña, 2= MA, 3= Ambas
	 */
	private Long idModalidadFk;
	
	/** 
	 * Constructor Vacío
	 */
	public SccMxMaeTipoProd() {
	}

	/**
	 * Constructor tipo de producto
	 * @param idTipoProductoPk
	 * llave
	 * @param dscTipoProducto
	 * descripcion
	 */
	public SccMxMaeTipoProd(Long idTipoProductoPk, String dscTipoProducto) {
		this.idTipoProductoPk = idTipoProductoPk;
		this.dscTipoProducto = dscTipoProducto;
	}

	/**
	 * @return Long idTipoProductoPk
	 */
	@Id
	@Column(name = "ID_TIPO_PRODUCTO_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdTipoProductoPk() {
		return this.idTipoProductoPk;
	}

	/**
	 * @param idTipoProductoPk Long
	 */
	public void setIdTipoProductoPk(Long idTipoProductoPk) {
		this.idTipoProductoPk = idTipoProductoPk;
	}

	/**
	 * @return String dscTipoProducto
	 */
	@Column(name = "DSC_TIPO_PRODUCTO", nullable = false, length = 100)
	public String getDscTipoProducto() {
		return this.dscTipoProducto;
	}

	/**
	 * @param dscTipoProducto String
	 */ 
	public void setDscTipoProducto(String dscTipoProducto) {
		this.dscTipoProducto = dscTipoProducto;
	}

	/**
	 * @return Long idAgrupadoConsumoFk
	 */
	@Column(name = "ID_AGRUPADO_CONSUMO_FK", nullable = false, length = 100)
	public Long getIdAgrupadoConsumoFk() {
		return idAgrupadoConsumoFk;
	}

	/**
	 * @param idAgrupadoConsumoFk Long
	 */
	public void setIdAgrupadoConsumoFk(Long idAgrupadoConsumoFk) {
		this.idAgrupadoConsumoFk = idAgrupadoConsumoFk;
	}

	/**
	 * @return Long idModalidadFk
	 */
	@Column(name = "ID_MODALIDAD_FK", nullable = false, length = 100)
	public Long getIdModalidadFk() {
		return idModalidadFk;
	}

	/**
	 * @param idModalidadFk Long
	 */
	public void setIdModalidadFk(Long idModalidadFk) {
		this.idModalidadFk = idModalidadFk;
	}

	
}
