package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Clase que se ocupa para manejar
 * la tabla catalogo de productos
 *  * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * 
 * 
 * SccMxMaeProducto generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_PRODUCTO")
public class SccMxMaeProducto implements IAbstractEntity, java.io.Serializable {


	/**
	 * Serializacion de la clase
	 */
	private static final long serialVersionUID = 7225201211802499360L;
	/**
	 * Llave principal para tabla producto
	 */
	private Long idProdPk;
	/**
	 * Conexion con tabla de amortizacion
	 */
	private Long idAmortiz;

	/**
	 * Conexion con modalidad por indice principal
	 */
	private SccMxMaeModalidad sccMxMaeModalidadByIdModalidadFk;
	/**
	 * Conexion con pago de seguro
	 */
	private SccMxMaePagoSeguro sccMxMaePagoSeguro;
	/**
	 * Conexion con tipo de consumo
	 */
	private SccMxMaeTipoConsumo sccMxMaeTipoConsumo;
	/**
	 * Conexion con tipo de producto
	 */
	private Long idTipoProd;
	/**
	 * Conexion con tipo de tasa
	 */
	private SccMxMaeTipoTasa sccMxMaeTipoTasa;
	/**
	 * Descripcion comercial del producto
	 */
	private String desProdComercial;
	/**
	 * Descripcion de la cobertura del seguro
	 */
	private String dscCoberturaSeg;
	/**
	 * Descripcion de las exclusiones del seguro
	 */
	private String dscExclusionSeg;
	/**
	 * Identificador de plantilla mandatorio
	 */
	private Long idPlnMandatorio;
	/**
	 * Descripcion de la periodicidad
	 */
	private String txtPeriodicidad;
	/**
	 * Identificador de la plantilla para tabla de amortizacion
	 */
	private Long idPlnTablaAmortiz;
	/**
	 * Identificador de la plantilla de la carta compromiso
	 */
	private Long idPlnCartaComp;
	/**
	 * Identificador de la plantilla manifestacion de no adeudo
	 */
	private Long idPlnNoadeudo;
	/**
	 * Descripcion de la cobertura del seguro
	 */
	private String dscCoberturaSegCc;
	/**
	 * Bandera que indica si aplica conversión auto
	 */
	private Long flgConvAuto;
	/**
	 * Descripcion de la entidad crediticia
	 */
	private String dscEntidadCrd;
	/**
	 * Codigo de producto
	 */
	private Long codProd;

	/**
	 * COnstructor Vacio
	 */
	public SccMxMaeProducto() {
	}

	/**
	 * Constructor con parametro llave
	 * @param idProdPk
	 * Llave
	 */
	public SccMxMaeProducto(Long idProdPk) {
		this.idProdPk = idProdPk;
	}




	@Id

	@Column(name = "ID_PROD_PK", unique = true, nullable = false, precision = 22, scale = 0)
	/**
	 * getter de id
	 * @return  idProdPk
	 * llave
	 */
	public Long getIdProdPk() {
		return this.idProdPk;
	}

	/**
	 * Setter de id
	 * @param idProdPk
	 * llave
	 */
	public void setIdProdPk(Long idProdPk) {
		this.idProdPk = idProdPk;
	}

	@Column(name = "ID_AMORTIZ_FK")
	/**
	 * Getter conexion
	 * @return idAmortiz
	 * tabla de amortizacion
	 */
	public Long getIdAmortiz() {
		return this.idAmortiz;
	}

	/**
	 * setter conexion
	 * @param idAmortiz
	 * tabla de amortizacion
	 */
	public void setIdAmortiz(Long idAmortiz) {
		this.idAmortiz = idAmortiz;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_MODALIDAD_FK")
	/**
	 * Otro join con modalidad
	 * @return sccMxMaeModalidadByIdModalidadFk
	 * tambien con la ofreigkn key 
	 */
	public SccMxMaeModalidad getSccMxMaeModalidadByIdModalidadFk() {
		return this.sccMxMaeModalidadByIdModalidadFk;
	}

	/**
	 * Hay modalidad por venta oferta y modalidad por tipo de modalidad
	 * @param sccMxMaeModalidadByIdModalidadFk
	 * esto se revisara en sprint 2
	 */
	public void setSccMxMaeModalidadByIdModalidadFk(SccMxMaeModalidad sccMxMaeModalidadByIdModalidadFk) {
		this.sccMxMaeModalidadByIdModalidadFk = sccMxMaeModalidadByIdModalidadFk;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_PAGO_SEGURO_FK")
	/**
	 * Conexion con pago de seguro
	 * @return sccMxMaePagoSeguro
	 * getter para el registro de cobro de seguro
	 */
	public SccMxMaePagoSeguro getSccMxMaePagoSeguro() {
		return this.sccMxMaePagoSeguro;
	}

	/**
	 * setter para conexion con pago de seguro
	 * @param sccMxMaePagoSeguro
	 * registro de pago de seguro
	 */
	public void setSccMxMaePagoSeguro(SccMxMaePagoSeguro sccMxMaePagoSeguro) {
		this.sccMxMaePagoSeguro = sccMxMaePagoSeguro;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_TIPO_CONSUMO_FK")
	/**
	 * getter para tipo consumo
	 * @return sccMxMaePagoSeguro
	 * registro de tipo de consumo
	 */
	public SccMxMaeTipoConsumo getSccMxMaeTipoConsumo() {
		return this.sccMxMaeTipoConsumo;
	}

	/**
	 * setter para tipo de consumo
	 * @param sccMxMaeTipoConsumo
	 * registro de conexion con tipo de consumo
	 */
	public void setSccMxMaeTipoConsumo(SccMxMaeTipoConsumo sccMxMaeTipoConsumo) {
		this.sccMxMaeTipoConsumo = sccMxMaeTipoConsumo;
	}

	@Column(name = "ID_TIPO_PRODUCTO_FK")
	/**
	 * getter de tipo de producto
	 * @return idTipoProd;
	 * conexion con tipo de prdocuto
	 */
	public Long getIdTipoProd() {
		return this.idTipoProd;
	}

	/**
	 * setter para tipo de producto
	 * @param idTipoProd
	 * registro de tipo de producto
	 */
	public void setIdTipoProd(Long idTipoProd) {
		this.idTipoProd = idTipoProd;
	}

	/**
	 * @return SccMxMaeTipoTasa sccMxMaeTipoTas
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_TIPO_TASA_FK")
	public SccMxMaeTipoTasa getSccMxMaeTipoTasa() {
		return this.sccMxMaeTipoTasa;
	}

	/**
	 * @param sccMxMaeTipoTasa SccMxMaeTipoTasa
	 */
	public void setSccMxMaeTipoTasa(SccMxMaeTipoTasa sccMxMaeTipoTasa) {
		this.sccMxMaeTipoTasa = sccMxMaeTipoTasa;
	}

	/**
	 * @return String desProdComercial
	 */
	@Column(name = "DES_PROD_COMERCIAL", length = 500)
	public String getDesProdComercial() {
		return this.desProdComercial;
	}

	/**
	 * @param desProdComercial String
	 */
	public void setDesProdComercial(String desProdComercial) {
		this.desProdComercial = desProdComercial;
	}

	/**
	 * @return String dscCoberturaSeg
	 */
	@Column(name = "DSC_COBERTURA_SEG", length = 500)
	public String getDscCoberturaSeg() {
		return this.dscCoberturaSeg;
	}

	/**
	 * @param dscCoberturaSeg String
	 */
	public void setDscCoberturaSeg(String dscCoberturaSeg) {
		this.dscCoberturaSeg = dscCoberturaSeg;
	}

	/**
	 * @return String dscExclusionSeg
	 */
	@Column(name = "DSC_EXCLUSION_SEG", length = 500)
	public String getDscExclusionSeg() {
		return this.dscExclusionSeg;
	}

	/**
	 * @param dscExclusionSeg String
	 */
	public void setDscExclusionSeg(String dscExclusionSeg) {
		this.dscExclusionSeg = dscExclusionSeg;
	}

	/**
	 * @return Long idPlnMandatorio
	 */
	@Column(name = "ID_PLN_MANDATORIO", precision = 22, scale = 0)
	public Long getIdPlnMandatorio() {
		return this.idPlnMandatorio;
	}

	/**
	 * @param idPlnMandatorio Long
	 */
	public void setIdPlnMandatorio(Long idPlnMandatorio) {
		this.idPlnMandatorio = idPlnMandatorio;
	}

	/**
	 * @return String txtPeriodicidad
	 */
	@Column(name = "TXT_PERIODICIDAD", length = 50)
	public String getTxtPeriodicidad() {
		return this.txtPeriodicidad;
	}

	/**
	 * @param txtPeriodicidad String
	 */
	public void setTxtPeriodicidad(String txtPeriodicidad) {
		this.txtPeriodicidad = txtPeriodicidad;
	}

	/**
	 * @return Long idPlnTablaAmortiz
	 */
	@Column(name = "ID_PLN_TABLA_AMORTIZ", precision = 22, scale = 0)
	public Long getIdPlnTablaAmortiz() {
		return this.idPlnTablaAmortiz;
	}

	/**
	 * @param idPlnTablaAmortiz Long
	 */
	public void setIdPlnTablaAmortiz(Long idPlnTablaAmortiz) {
		this.idPlnTablaAmortiz = idPlnTablaAmortiz;
	}

	/**
	 * @return Long idPlnCartaComp
	 */
	@Column(name = "ID_PLN_CARTA_COMP", precision = 22, scale = 0)
	public Long getIdPlnCartaComp() {
		return this.idPlnCartaComp;
	}

	/**
	 * @param idPlnCartaComp Long
	 */
	public void setIdPlnCartaComp(Long idPlnCartaComp) {
		this.idPlnCartaComp = idPlnCartaComp;
	}

	/**
	 * @return Long idPlnNoadeudo
	 */
	@Column(name = "ID_PLN_NOADEUDO", precision = 22, scale = 0)
	public Long getIdPlnNoadeudo() {
		return this.idPlnNoadeudo;
	}

	/**
	 * @param idPlnNoadeudo Long
	 */
	public void setIdPlnNoadeudo(Long idPlnNoadeudo) {
		this.idPlnNoadeudo = idPlnNoadeudo;
	}

	/**
	 * @return String dscCoberturaSegCc
	 */
	@Column(name = "DSC_COBERTURA_SEG_CC", length = 500)
	public String getDscCoberturaSegCc() {
		return this.dscCoberturaSegCc;
	}

	/**
	 * @param dscCoberturaSegCc String
	 */
	public void setDscCoberturaSegCc(String dscCoberturaSegCc) {
		this.dscCoberturaSegCc = dscCoberturaSegCc;
	}

	/**
	 * @return Long flgConvAuto
	 */
	@Column(name = "FLG_CONV_AUTO", precision = 22, scale = 0)
	public Long getFlgConvAuto() {
		return this.flgConvAuto;
	}

	/**
	 * @param flgConvAuto Long
	 */
	public void setFlgConvAuto(Long flgConvAuto) {
		this.flgConvAuto = flgConvAuto;
	}

	/**
	 * @return String dscEntidadCrd
	 */
	@Column(name = "DSC_ENTIDAD_CRD", length = 500)
	public String getDscEntidadCrd() {
		return this.dscEntidadCrd;
	}

	/**
	 * @param dscEntidadCrd String
	 */
	public void setDscEntidadCrd(String dscEntidadCrd) {
		this.dscEntidadCrd = dscEntidadCrd;
	}

	/**
	 * @return Long codProd
	 */
	@Column(name = "COD_PROD", precision = 22, scale = 0)
	public Long getCodProd() {
		return this.codProd;
	}

	/**
	 * @param codProd Long
	 */
	public void setCodProd(Long codProd) {
		this.codProd = codProd;
	}


}
