package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 *  Entidad para los plazos, que existen en relacion de 
 * uno a muchos con las tasas. Esto es, una tasa contiene
 * hasta doce plazos, y una campaña contiene hasta tres tasas
 * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * SccMxPrcOferMaxPlzo generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_PRC_OFER_MAX_PLZO")
public class SccMxPrcOferMaxPlzo implements IAbstractEntity, java.io.Serializable {


	/**
	 * serializacion de la entidad SccMxPrcOferMaxPlzo
	 */
	private static final long serialVersionUID = 2556254378708402280L;
	/**
	 * Llave primaria, unica y secuencial de la entidad SccMxPrcOferMaxPlzo
	 */
	private Long idOferMaxPlzoPk;
	/**
	 * propiedad sccMxMaeOferCam de la entidad SccMxPrcOferMaxPlzo
	 * Relacion con el objeto de campania
	 */
	private SccMxMaeOferCam sccMxMaeOferCam;
	/**
	 * propiedad sccMxPrcOferMaxTasa de la entidad SccMxPrcOferMaxPlzo
	 * Relacin con el objeto de tasas
	 */
	private SccMxPrcOferMaxTasa sccMxPrcOferMaxTasa;
	/**
	 * Codigo de Plazo: Base, 1, 2.. hasta 12
	 */
	private String codPlzo;
	/**
	 * Cantidad en Meses correspondiente al plazo indicado
	 */
	private Long canPlzo;
	/**
	 * Monto del Prestamo maximo correspondiente al plazo indicado
	 */
	private Double impMonto;

	/**
	 * Constructor vac_o
	 */
	public SccMxPrcOferMaxPlzo() {
	}

	/**
	 * Constructor de ofertas maximas por plazo
	 * @param idOferMaxPlzoPk
	 * llave
	 */
	public SccMxPrcOferMaxPlzo(Long idOferMaxPlzoPk) {
		this.idOferMaxPlzoPk = idOferMaxPlzoPk;
	}

	/**
	 * Constructor completo
	 * @param idOferMaxPlzoPk
	 * llave
	 * @param sccMxMaeOferCam
	 * conexion con ofertas de campa_a
	 * @param sccMxPrcOferMaxTasa
	 * conexion con tabla de ofertas maximas
	 * @param codPlzo
	 * Codigo de plazo
	 * @param canPlzo
	 * cantidad 
	 * @param impMonto
	 * monto
	 */
	public SccMxPrcOferMaxPlzo(Long idOferMaxPlzoPk, SccMxMaeOferCam sccMxMaeOferCam,
			SccMxPrcOferMaxTasa sccMxPrcOferMaxTasa, String codPlzo, Long canPlzo, Double impMonto) {
		this.idOferMaxPlzoPk = idOferMaxPlzoPk;
		this.sccMxMaeOferCam = sccMxMaeOferCam;
		this.sccMxPrcOferMaxTasa = sccMxPrcOferMaxTasa;
		this.codPlzo = codPlzo;
		this.canPlzo = canPlzo;
		this.impMonto = impMonto;
	}

	/**
	 * @return Long idOferMaxPlzoPk
	 */
	@Id
	@Column(name = "ID_OFER_MAX_PLZO_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdOferMaxPlzoPk() {
		return this.idOferMaxPlzoPk;
	}

	/**
	 * Este es el dato para la llave primaria
	 * @param idOferMaxPlzoPk
	 * es igual en getter y setter
	 */
	public void setIdOferMaxPlzoPk(Long idOferMaxPlzoPk) {
		this.idOferMaxPlzoPk = idOferMaxPlzoPk;
	}

	/**
	 * @return SccMxMaeOferCam sccMxMaeOferCam
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_OFER_CAM_FK")
	public SccMxMaeOferCam getSccMxMaeOferCam() {
		return this.sccMxMaeOferCam;
	}

	/**
	 * Conexion con registro de ofertas de campaña
	 * @param sccMxMaeOferCam
	 * Registro de la tabla de ofertas de campaña
	 */
	public void setSccMxMaeOferCam(SccMxMaeOferCam sccMxMaeOferCam) {
		this.sccMxMaeOferCam = sccMxMaeOferCam;
	}

	/**
	 * @return SccMxPrcOferMaxTasa sccMxPrcOferMaxTasa
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_OFER_MAX_TASA_FK")
	public SccMxPrcOferMaxTasa getSccMxPrcOferMaxTasa() {
		return this.sccMxPrcOferMaxTasa;
	}

	/** 
	 * conexion con la tabla de las tasas
	 * @param sccMxPrcOferMaxTasa
	 * Registro de la tasa
	 */
	public void setSccMxPrcOferMaxTasa(SccMxPrcOferMaxTasa sccMxPrcOferMaxTasa) {
		this.sccMxPrcOferMaxTasa = sccMxPrcOferMaxTasa;
	}

	/**
	 * @return String codPlzo
	 */
	@Column(name = "COD_PLZO", length = 20)
	public String getCodPlzo() {
		return this.codPlzo;
	}

	/**
	 * @param codPlzo String
	 */
	public void setCodPlzo(String codPlzo) {
		this.codPlzo = codPlzo;
	}

	/**
	 * @return Long canPlzo
	 */
	@Column(name = "CAN_PLZO", precision = 22, scale = 0)
	public Long getCanPlzo() {
		return this.canPlzo;
	}

	/**
	 * @param canPlzo Long
	 */
	public void setCanPlzo(Long canPlzo) {
		this.canPlzo = canPlzo;
	}

	/**
	 * @return Double impMonto
	 */
	@Column(name = "IMP_MONTO", precision = 22, scale = 0)
	public Double getImpMonto() {
		return this.impMonto;
	}

	/**
	 * @param impMonto Double
	 */
	public void setImpMonto(Double impMonto) {
		this.impMonto = impMonto;
	}

}
