package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clase para relacionar con la tabla
 * de periodicidades que indica si se maneja
 * Mensual, Semanal, Quincenal, etc
  * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * SccMxMaePeriod generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_PERIOD")
public class SccMxMaePeriod implements IAbstractEntity, java.io.Serializable {


	/**
	 * Identificador para serializar la clase
	 */
	private static final long serialVersionUID = 3825152038057594169L;
	/**
	 * Identificador de la llave primaria
	 */
	private Long idPeriodPk;
	/**
	 * Descripción de la periodicidad
	 */
	private String dscPeriod;
	/**
	 * Numero de dias de la periodicidad
	 */
	private Long numDiasPeriod;
	/**
	 * Codigo del periodo puede ser M, Q, C, S
	 */
	private String codPeriod;

	/**
	 * Constructor vacio
	 */
	public SccMxMaePeriod() {
	}

	/**
	 * Constructor con llave
	 * @param idPeriodPk
	 * llave
	 */
	public SccMxMaePeriod(Long idPeriodPk) {
		this.idPeriodPk = idPeriodPk;
	}

	/**
	 * Constructor para la tabla de periodicidades
	 * @param idPeriodPk
	 * Primary key
	 * @param dscPeriod
	 * descripción
	 * @param numDiasPeriod
	 * Numero de dias del periodo
	 * @param codPeriod
	 * codigo del periodo
	 */
	public SccMxMaePeriod(Long idPeriodPk, String dscPeriod, Long numDiasPeriod, String codPeriod) {
		this.idPeriodPk = idPeriodPk;
		this.dscPeriod = dscPeriod;
		this.numDiasPeriod = numDiasPeriod;
		this.codPeriod = codPeriod;
	}

	/**
	 * @return Long idPeriodPk Id del periodo
	 */
	@Id

	@Column(name = "ID_PERIOD_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdPeriodPk() {
		return this.idPeriodPk;
	}

	/**
	 * @param idPeriodPk Long Id del periodo
	 */
	public void setIdPeriodPk(Long idPeriodPk) {
		this.idPeriodPk = idPeriodPk;
	}

	/**
	 * @return String dscPeriod Nombre del periodo
	 */
	@Column(name = "DSC_PERIOD", length = 100)
	public String getDscPeriod() {
		return this.dscPeriod;
	}

	/**
	 * @param dscPeriod String Nombre del periodo
	 */
	public void setDscPeriod(String dscPeriod) {
		this.dscPeriod = dscPeriod;
	}

	/**
	 * @return Long numDiasPeriod Número de días del periodo
	 */
	@Column(name = "NUM_DIAS_PERIOD", precision = 22, scale = 0)
	public Long getNumDiasPeriod() {
		return this.numDiasPeriod;
	}

	/**
	 * @param numDiasPeriod Long Número de días del periodo
	 */
	public void setNumDiasPeriod(Long numDiasPeriod) {
		this.numDiasPeriod = numDiasPeriod;
	}
	
	/**
	 * @return String codPeriod Código de periodo
	 */
	@Column(name = "COD_PERIOD", length = 100)
	public String getCodPeriod() {
		return codPeriod;
	}

	/**
	 * @param codPeriod String Código de periodo
	 */
	public void setCodPeriod(String codPeriod) {
		this.codPeriod = codPeriod;
	}


}
