package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * 
 * Generado por GlobalHitss
 * Fabrica de Software
 * Proyecto Santander SImulador de Credito al Consumo
 * Mayo 2019
 * Sprint 1
 * 
 * 
 * SccMxMaeOferPromMa generated by hbm2java
 * Entidad que conserva la informacion de ofertas promocionales
 * para mercado abierto
 * Aplican por Buc o por Subproducto
 */
@Entity
@Table(name = "SCC_MX_MAE_OFER_PROM_MA")
public class SccMxMaeOferPromMa implements IAbstractEntity, java.io.Serializable {

	
	/**
	 * Identificador para serializar la clase
	 */
	private static final long serialVersionUID = -1214383519359919128L;
	/**
	 * Llave primaria de ofertas promocionales
	 */
	private Long idOferPromPk;
	/**
	 * Para conectar con registro de tabla comisión
	 */
	private Long idComision;
	/**
	 * Para conectar con registro de tabla producto
	 */
	private Long idProducto;
	/**
	 * Para conectar con registro de tabla subproducto
	 */
	private long idSubProd;
	/**
	 * Buc del cliente
	 */
	private Long idBucClte;
	/**
	 * Fecha inicial de la promoción
	 */
	private Date fchIniProm;
	/**
	 * Fecha final de la promoción
	 */
	private Date fchFinProm;
	/**
	 * Nombre del cliente
	 */
	private String dscNomClte;
	/**
	 * Porcentaje de tasa interes minimo
	 */
	private Double porTasaIntPromMin;
	/**
	 * Porcentaje de tasa de interes base
	 */
	private Double porTasaIntBaseResta;
	/**
	 * Nombre de la promoción
	 */
	private String dscNomProm;
	/** 
	 * Identificador de la plantilla de certificado de descuento
	 */
	private Long idPlnCertifDscto;
	/**
	 * nombre
	 */
	private String txtNomColec;
	/**
	 * Porcentaje del CAT promocional
	 */
	private Long porCatProm;
	/**
	 * Descripción de entidad crediticia
	 */
	private String dscEntiCrd;
	/**
	 * Porcentaje de comision promocional
	 */
	private Double porComPromo;
	/**
	 * Descripción de comision promocional
	 */
	private String dscComPromo;
	/**
	 * Codigo de acceso para perfil Venta CCS se usa en conjunto con codvtacssout
	 */
	private Long codVtaCcsIn;
	/**
	 * Codigo de acceso para perfil venta ccs
	 */
	private Long codVtaCcsOut;
	/**
	 * Codigo de acceso para perfil venta red se usa enconjunto con codvtaredin
	 */
	private Long codVtaRedIn;
	/**
	 * codigo de acceso para perfil venta red
	 */
	private Long codVtaRedOut;
	/**
	 * Codigo de acceso para perfil Fuerza de Ventas (integra ASN) se usa en conjunto con codvtafve
	 */
	private Long codVtaAsn;
	/**
	 * Codigo de acceso para perfil venta fve
	 */
	private Long codVtaFve;
	/**
	 * Codigo de plantilla mandatorio
	 */
	private Long idPlanMandatorio;
	/**
	 * Constructor Vacio
	 */
	public SccMxMaeOferPromMa() {
	}

	/**
	 * Constructor de ofertas promocionales de mercado abierto
	 * @param idOferPromPk
	 * Id primary key
	 * @param idProducto
	 * conexion tabla producto
	 * @param idSubProd
	 * conexion tabla subproducto
	 * @param idBucClte
	 * BUC del cliente
	 */
	public SccMxMaeOferPromMa(Long idOferPromPk, Long idProducto, Long idSubProd,
			Long idBucClte) {
		this.idOferPromPk = idOferPromPk;
		this.idProducto = idProducto;
		this.idSubProd = idSubProd;
		this.idBucClte = idBucClte;
	}

	@Id
	@Column(name = "ID_OFER_PROM_PK", unique = true, nullable = false, precision = 22, scale = 0)
	/**
	 * Getter de llave
	 * @return idOferPromPk
	 * llave
	 */
	public Long getIdOferPromPk() {
		return this.idOferPromPk;
	}
	
	
	/**
	 * Setter llave
	 * @param idOferPromPk
	 * Llave
	 */
	public void setIdOferPromPk(Long idOferPromPk) {
		this.idOferPromPk = idOferPromPk;
	}

	@Column(name = "ID_COM_PROMO_FK")
	/**
	 * Getter de comision
	 * @return idComision
	 * Conexion con la tabla de comisiones
	 */
	public Long getIdComision() {
		return this.idComision;
	}

	/**
	 * Setter de comision
	 * @param idComision
	 * Conexion con comision
	 */
	public void setIdComision(Long idComision) {
		this.idComision = idComision;
	}

	@Column(name = "ID_PROD_FK")
	/**
	 * Getter de producto
	 * @return idProducto
	 * Conexion con producto -tabla
	 */
	public Long getIdProducto() {
		return this.idProducto;
	}

	/**
	 * Setter para conexion con producto
	 * @param idProducto
	 * registro de producto
	 */
	public void setIdProducto(Long idProducto) {
		this.idProducto = idProducto;
	}

	/**
	 * Conexion con tabla subproducto
	 * @param idSubProd
	 * registro de subroductos
	 */
	public void setIdSubProd(Long idSubProd) {
		this.idSubProd = idSubProd;
	}
	
	@Column(name = "ID_SUB_PROD_FK")
	/**
	 * Conexion con subproducto
	 * @return idSubProd
	 * regresa registro de subproducto
	 */
	public Long getIdSubProd() {
		return this.idSubProd;
	}

	/**
	 * setter de buc
	 * @param idBucClte
	 * buc del cliente
	 */
	public void setIdBucClte(Long idBucClte) {
		this.idBucClte = idBucClte;
	}

	@Column(name = "ID_BUC_CLTE", nullable = false, precision = 22, scale = 0)
	/**
	 * Buc del cliente
	 * @return idBucClte
	 * identificador del cliente
	 */
	public Long getIdBucClte() {
		return this.idBucClte;
	}

	/**
	 * Fecha de inicio de la promocion
	 * @param fchIniProm
	 * Setter de fecha inicio
	 */
	public void setFchIniProm(Date fchIniProm) {
		this.fchIniProm = new Date(fchIniProm.getTime());
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FCH_INI_PROM", length = 11)
	/**
	 * Getter de la fecha inicial
	 * @return Date
	 * regresa la fecha inicial de la promocion
	 */
	public Date getFchIniProm() {
		return new Date(this.fchIniProm.getTime());
	}

	/**
	 * Setter de la fecha final
	 * @param fchFinProm
	 * Fecha final de promocion
	 */
	public void setFchFinProm(Date fchFinProm) {
		this.fchFinProm = new Date(fchFinProm.getTime());
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FCH_FIN_PROM", length = 11)
	/**
	 * Getter de la fecha final
	 * @return Date
	 * Fecha final de la promocion
	 */
	public Date getFchFinProm() {
		return new Date(this.fchFinProm.getTime());
	}

	@Column(name = "DSC_NOM_CLTE", length = 100)
	/**
	 * Getter de la descripcion 
	 * @return dscNomClte
	 * Nombre del cliente
	 */
	public String getDscNomClte() {
		return this.dscNomClte;
	}

	/**
	 * Setter de la descripcion
	 * @param dscNomClte
	 * Nombre del cliente
	 */
	public void setDscNomClte(String dscNomClte) {
		this.dscNomClte = dscNomClte;
	}

	@Column(name = "POR_TASA_INT_PROM_MIN", precision = 22, scale = 2)
	/**
	 * Getter porcentaje de tasa
	 * @return porTasaIntPromMin
	 * Porcentaje tasa de interes min
	 */
	public Double getPorTasaIntPromMin() {
		return this.porTasaIntPromMin;
	}

	/**
	 * Setter porcentaje de tasa
	 * @param porTasaIntPromMin
	 * porcentaje de tasa 
	 */
	public void setPorTasaIntPromMin(Double porTasaIntPromMin) {
		this.porTasaIntPromMin = porTasaIntPromMin;
	}

	/**
	 * setter porcentaje de tasa
	 * @param porTasaIntBaseResta
	 * tasa que se debe restar
	 */
	public void setPorTasaIntBaseResta(Double porTasaIntBaseResta) {
		this.porTasaIntBaseResta = porTasaIntBaseResta;
	}

	@Column(name = "POR_TASA_INT_BASE_RESTA", precision = 22, scale = 2)
	/**
	 * Getter porcentaje de tasa de interes
	 * @return porTasaIntBaseResta
	 * Porcentaje de tasa de interes para restar
	 */
	public Double getPorTasaIntBaseResta() {
		return this.porTasaIntBaseResta;
	}

	/**
	 * Setter nombre cliente
	 * @param dscNomProm
	 * descripcion nombre de cliente
	 */
	public void setDscNomProm(String dscNomProm) {
		this.dscNomProm = dscNomProm;
	}

	@Column(name = "DSC_NOM_PROM", length = 100)
	/**
	 * Getter nombre
	 * @return dscNomProm
	 * descripcion, nombre de promocion
	 */
	public String getDscNomProm() {
		return this.dscNomProm;
	}

	/**
	 * @param idPlnCertifDscto Long
	 */
	public void setIdPlnCertifDscto(Long idPlnCertifDscto) {
		this.idPlnCertifDscto = idPlnCertifDscto;
	}

	/**
	 * @return Long idPlnCertifDscto
	 */
	@Column(name = "ID_PLN_CERTIF_DSCTO", precision = 22, scale = 0)
	public Long getIdPlnCertifDscto() {
		return this.idPlnCertifDscto;
	}

	/**
	 * @param txtNomColec String
	 */
	public void setTxtNomColec(String txtNomColec) {
		this.txtNomColec = txtNomColec;
	}

	/**
	 * @return  String txtNomColec
	 */
	@Column(name = "TXT_NOM_COLEC", length = 100)
	public String getTxtNomColec() {
		return this.txtNomColec;
	}

	/**
	 * @return Long porCatProm
	 */
	@Column(name = "POR_CAT_PROM", precision = 22, scale = 0)
	public Long getPorCatProm() {
		return this.porCatProm;
	}

	/**
	 * @param porCatProm Long
	 */
	public void setPorCatProm(Long porCatProm) {
		this.porCatProm = porCatProm;
	}

	/**
	 * @return String dscEntiCrd
	 */
	@Column(name = "DSC_ENTI_CRD", length = 100)
	public String getDscEntiCrd() {
		return this.dscEntiCrd;
	}

	/**
	 * @param dscEntiCrd String
	 */
	public void setDscEntiCrd(String dscEntiCrd) {
		this.dscEntiCrd = dscEntiCrd;
	}

	/**
	 * @param porComPromo Double
	 */
	public void setPorComPromo(Double porComPromo) {
		this.porComPromo = porComPromo;
	}

	/**
	 * @return Double porComPromo
	 */
	@Column(name = "POR_COM_PROMO", precision = 22, scale = 0)
	public Double getPorComPromo() {
		return this.porComPromo;
	}

	/**
	 * @param dscComPromo String
	 */
	public void setDscComPromo(String dscComPromo) {
		this.dscComPromo = dscComPromo;
	}

	/**
	 * @return String dscComPromo
	 */
	@Column(name = "DSC_COM_PROMO", length = 100)
	public String getDscComPromo() {
		return this.dscComPromo;
	}

	/**
	 * @param codVtaCcsIn Long
	 */
	public void setCodVtaCcsIn(Long codVtaCcsIn) {
		this.codVtaCcsIn = codVtaCcsIn;
	}

	/**
	 * @return Long codVtaCcsIn
	 */
	@Column(name = "COD_VTA_CCS_IN", precision = 22, scale = 0)
	public Long getCodVtaCcsIn() {
		return this.codVtaCcsIn;
	}

	/**
	 * @param codVtaCcsOut Long
	 */
	public void setCodVtaCcsOut(Long codVtaCcsOut) {
		this.codVtaCcsOut = codVtaCcsOut;
	}

	/**
	 * @return Long codVtaCcsOut
	 */
	@Column(name = "COD_VTA_CCS_OUT", precision = 22, scale = 0)
	public Long getCodVtaCcsOut() {
		return this.codVtaCcsOut;
	}

	/**
	 * @param codVtaRedIn Long
	 */
	public void setCodVtaRedIn(Long codVtaRedIn) {
		this.codVtaRedIn = codVtaRedIn;
	}

	/**
	 * @return Long codVtaRedIn 
	 */
	@Column(name = "COD_VTA_RED_IN", precision = 22, scale = 0)
	public Long getCodVtaRedIn() {
		return this.codVtaRedIn;
	}

	/**
	 * @param codVtaRedOut Long
	 */
	public void setCodVtaRedOut(Long codVtaRedOut) {
		this.codVtaRedOut = codVtaRedOut;
	}

	/**
	 * @return Long codVtaRedOut
	 */
	@Column(name = "COD_VTA_RED_OUT", precision = 22, scale = 0)
	public Long getCodVtaRedOut() {
		return this.codVtaRedOut;
	}

	/**
	 * @param codVtaAsn Long
	 */
	public void setCodVtaAsn(Long codVtaAsn) {
		this.codVtaAsn = codVtaAsn;
	}

	/**
	 * @return Long codVtaAsn
	 */
	@Column(name = "COD_VTA_ASN", precision = 22, scale = 0)
	public Long getCodVtaAsn() {
		return this.codVtaAsn;
	}

	/**
	 * @param codVtaFve Long
	 */
	public void setCodVtaFve(Long codVtaFve) {
		this.codVtaFve = codVtaFve;
	}

	/**
	 * @return Long codVtaFve
	 */
	@Column(name = "COD_VTA_FVE", precision = 22, scale = 0)
	public Long getCodVtaFve() {
		return this.codVtaFve;
	}
	
	/**
	 * @return Long idPlanMandatorio
	 */
	@Column(name = "ID_PLN_MANDATORIO", precision = 22, scale = 0)
	public Long getIdPlanMandatorio() {
		return this.idPlanMandatorio;
	}
	
	
	/**
	 * @param idPlanMandatorio Long
	 */
	public void setIdPlanMandatorio(Long idPlanMandatorio) {
		this.idPlanMandatorio = idPlanMandatorio;
	}

}
