package mx.isban.scc.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Catalogo con los tres tipos de usuario
 * definidos por Santander
 * Administrador, Consulta y Comercial
 * Generado por GlobalHitss
* Mayo 2019
* Sprint 1
* 
* SccMxMaeTipoUsr generated by hbm2java
* @author Hitss
*/
@Entity
@Table(name = "SCC_MX_MAE_TIPO_USR")
public class SccMxMaeTipoUsr implements IAbstractEntity, Serializable {

	/**
	 * variable con finalidad de serializar
	 */
	private static final long serialVersionUID = 3579396078816471614L;
	
	/**
	 * Llave principal y unica del tipo de usuario
	 */
	@Id
	private Long idTipoUsrPk;
	/**
	 * descripcion del tipo: Comercial, Administrador, consulta
	 */
	private String dscTipo;

	/**
	 * constructor de la clase
	 */
	public SccMxMaeTipoUsr() {
	}

	/**
	 * constructor con parametros
	 * 
	 * @param idTipoUsrPk idTipoUsr
	 * @param dscTipo descripcion
	 */
	public SccMxMaeTipoUsr(Long idTipoUsrPk, String dscTipo) {
		super();
		this.idTipoUsrPk = idTipoUsrPk;
		this.dscTipo = dscTipo;
	}

	/**
	 * @return Long idTipoUsrPk
	 */
	public Long getIdTipoUsrPk() {
		return idTipoUsrPk;
	}

	/**
	 * @param idTipoUsrPk Long
	 */
	public void setIdTipoUsrPk(Long idTipoUsrPk) {
		this.idTipoUsrPk = idTipoUsrPk;
	}

	/**
	 * @return String dscTipo
	 */
	public String getDscTipo() {
		return dscTipo;
	}

	/**
	 * @param dscTipo String
	 */
	public void setDscTipo(String dscTipo) {
		this.dscTipo = dscTipo;
	}

}
