package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entidad modelo de la tabla SCC_MX_MAE_OFER_PROM_CAM
 * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * SccMxMaeOferPromCam generated by hbm2java
 * Contiene la informacion de ofertas promocionales aunadas a la oferta de campania ya existente
 * puede relacionarse por BUC de cliente o por el Subproducto indicado en la oferta de campania
 */
@Entity
@Table(name = "SCC_MX_MAE_OFER_PROM_CAM")
public class SccMxMaeOferPromCam implements IAbstractEntity, java.io.Serializable {


	/**
	 * variable serializadora
	 */
	private static final long serialVersionUID = -727651606818975110L;
	/**
	 * oferta cam
	 */
	private Long idOferPreCamPk;
	/**
	 * Identificador comision
	 */
	private Long idComision;
	/**
	 * Identificador producto
	 */
	private Long idProducto;
	/**
	 * Identificador subproducto
	 */
	private Long idSubProd;
	/**
	 * Identificador cliente
	 */
	private Long idBucClte;
	/**
	 * nombre cliente
	 */
	private String dscNomClte;
	/**
	 * procentaje tasa
	 */
	private Double porTasaIntProm;
	/**
	 * porsentaje tasa base
	 */
	private Double porTasaIntBase;
	/**
	 * nombre promocion
	 */
	private String dscNomProm;
	/**
	 * certificado descuento id
	 */
	private Long idPlnCertifDscto;
	/**
	 * nombre colectivo
	 */
	private String txtNomColectivo;
	/**
	 * fecha inicio promocion
	 */
	private Date fchIniProm;
	/**
	 * fecha fin promocion
	 */
	private Date fchFinProm;
	/**
	 * cat promocional
	 */
	private Long porCatProm;
	/**
	 * entidad
	 */
	private String dscEntidadCrd;
	/**
	 * porcentaje comision promo
	 */
	private Double porComPromo;
	/**
	 * descripcion comision promo
	 */
	private String dscComPromo;
	/**
	 * numero de lapa
	 */
	private Long numLapa;
	/**
	 * nombre tarjeta
	 */
	private String txtNomTarjeta;
	/**
	 * numero tarjeta
	 */
	private String txtNumTarjeta;
	/**
	 * seguro promocional
	 */
	private Long porFacAsegPromo;
	/**
	 * codVtaCcsIn Indicador de visibilidad junto con codvtaccsout para Contact Center
	 */
	private Long codVtaCcsIn;
	/**
	 * codVtaCcsOut Indicador de visibilidad junto con codvtaccs in para Contact center
	 */
	private Long codVtaCcsOut;
	/**
	 * codVtaRedIn Indicador de visibilidad junto con codvtaredout para usuarios comerciales sucursal
	 */
	private Long codVtaRedIn;
	/**
	 * codVtaRedOut Indicador de visiblidad junto con codvtaredin para usuarios comerciales sucursal
	 */
	private Long codVtaRedOut;
	/**
	 * codVtaAsn Indicador de visibilidad junto con codvtafve para usuarios Fuerza de Ventas
	 */
	private Long codVtaAsn;
	/**
	 * codVtaFve Indicador de visibilidad junto con codvtaasn para usuarios fuerza de ventas
	 */
	private Long codVtaFve;
	/**
	 * Codigo de plantilla mandatorio
	 */
	private Long idPlanMandatorio;

	/**
	 * Constructor por default sin parámetros que permite 
	 * construir una instancia de ésta clase denominada SccMxMaeOferPromCam
	 */
	public SccMxMaeOferPromCam() {
		super();
	}


	/**
	 * @return Long idOferPreCamPk Parent Key
	 */
	@Id
	@Column(name = "ID_OFER_PRE_CAM_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdOferPreCamPk() {
		return this.idOferPreCamPk;
	}

	/**
	 * @param idOferPreCamPk
	 */
	public void setIdOferPreCamPk(Long idOferPreCamPk) {
		this.idOferPreCamPk = idOferPreCamPk;
	}
	/**
	 * @return Long idComision Parent Key
	 */
	@Column(name = "ID_COM_PROMO_FK")
	public Long getIdComision() {
		return this.idComision;
	}

	/**
	 * @param idComision Long Parent Key
	 */
	public void setIdComision(Long idComision) {
		this.idComision = idComision;
	}

	/**
	 * @return Long idProducto Id de producto
	 */
	@Column(name = "ID_PROD_FK")
	public Long getIdProducto() {
		return this.idProducto;
	}

	/**
	 * @param idProducto Long Id de producto
	 */
	public void setIdProducto(Long idProducto) {
		this.idProducto = idProducto;
	}

	/**
	 * @return Long idSubProd Id de subproducto
	 */
	@Column(name = "ID_SUB_PROD_FK")
	public Long getIdSubProd() {
		return this.idSubProd;
	}

	/**
	 * @param idSubProd Long Id de subproducto
	 */
	public void setIdSubProd(Long idSubProd) {
		this.idSubProd = idSubProd;
	}

	/**
	 * @return Long idBucClte Id de cliente
	 */
	@Column(name = "ID_BUC_CLTE", nullable = false, precision = 22, scale = 0)
	public Long getIdBucClte() {
		return this.idBucClte;
	}

	/**
	 * @param idBucClte Long Id de cliente
	 */
	public void setIdBucClte(Long idBucClte) {
		this.idBucClte = idBucClte;
	}

	/**
	 * @return String dscNomClte Nombre del cliente
	 */
	@Column(name = "DSC_NOM_CLTE", length = 100)
	public String getDscNomClte() {
		return this.dscNomClte;
	}

	/**
	 * @param dscNomClte String Nombre del cliente
	 */
	public void setDscNomClte(String dscNomClte) {
		this.dscNomClte = dscNomClte;
	}

	/**
	 * @return Double porTasaIntProm Tasa de interés promedio
	 */
	@Column(name = "POR_TASA_INT_PROM", precision = 22, scale = 2)
	public Double getPorTasaIntProm() {
		return this.porTasaIntProm;
	}

	/**
	 * @param porTasaIntProm Double Tasa de interés promedio
	 */
	public void setPorTasaIntProm(Double porTasaIntProm) {
		this.porTasaIntProm = porTasaIntProm;
	}

	/**
	 * @param porTasaIntBase Double Tasa de interés base
	 */
	public void setPorTasaIntBase(Double porTasaIntBase) {
		this.porTasaIntBase = porTasaIntBase;
	}

	/**
	 * @return Double porTasaIntBase Tasa de interés base
	 */
	@Column(name = "POR_TASA_INT_BASE", precision = 22, scale = 2)
	public Double getPorTasaIntBase() {
		return this.porTasaIntBase;
	}

	/**
	 * @param dscNomProm String Nombre promoción
	 */
	public void setDscNomProm(String dscNomProm) {
		this.dscNomProm = dscNomProm;
	}

	/**
	 * @return String dscNomProm  Nombre promoción
	 */
	@Column(name = "DSC_NOM_PROM", length = 100)
	public String getDscNomProm() {
		return this.dscNomProm;
	}

	/**
	 * @param idPlnCertifDscto Long
	 */
	public void setIdPlnCertifDscto(Long idPlnCertifDscto) {
		this.idPlnCertifDscto = idPlnCertifDscto;
	}

	/**
	 * @return Long idPlnCertifDscto Id del certificado de descuento del plan
	 */
	@Column(name = "ID_PLN_CERTIF_DSCTO", precision = 22, scale = 0)
	public Long getIdPlnCertifDscto() {
		return this.idPlnCertifDscto;
	}

	/**
	 * @param txtNomColectivo String Nombre del Plan Colectivo
	 */
	public void setTxtNomColectivo(String txtNomColectivo) {
		this.txtNomColectivo = txtNomColectivo;
	}

	/**
	 * @return String txtNomColectivo Nombre del Plan Colectivo
	 */
	@Column(name = "TXT_NOM_COLECTIVO", length = 100)
	public String getTxtNomColectivo() {
		return this.txtNomColectivo;
	}

	/**
	 * @param fchIniProm Date Fecha de inicio de la promocion
	 */
	public void setFchIniProm(Date fchIniProm) {
		this.fchIniProm = new Date(fchIniProm.getTime());
	}

	/**
	 * @return Date fchIniProm  Fecha de inicio de la promocion
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FCH_INI_PROM", length = 11)
	public Date getFchIniProm() {
		return new Date(this.fchIniProm.getTime());
	}

	/**
	 * @param fchFinProm Date Fecha de fin de la promocion 
	 */
	public void setFchFinProm(Date fchFinProm) {
		this.fchFinProm = new Date(fchFinProm.getTime());
	}

	/**
	 * @return fchFinProm Date Fecha de fin de la promocion
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FCH_FIN_PROM", length = 11)
	public Date getFchFinProm() {
		return new Date(this.fchFinProm.getTime());
	}

	/**
	 * @return Long porCatProm CAT promedio
	 */
	@Column(name = "POR_CAT_PROM", precision = 22, scale = 0)
	public Long getPorCatProm() {
		return this.porCatProm;
	}

	/**
	 * @param porCatProm Long CAT promedio
	 */
	public void setPorCatProm(Long porCatProm) {
		this.porCatProm = porCatProm;
	}

	/**
	 * @return String dscEntidadCrd Nombre de la entidad crediticia
	 */
	@Column(name = "DSC_ENTIDAD_CRD", length = 100)
	public String getDscEntidadCrd() {
		return this.dscEntidadCrd;
	}

	/**
	 * @param dscEntidadCrd String Nombre de la entidad crediticia
	 */ 
	public void setDscEntidadCrd(String dscEntidadCrd) {
		this.dscEntidadCrd = dscEntidadCrd;
	}

	/**
	 * @return Double porComPromo Comisión promocional
	 */
	@Column(name = "POR_COM_PROMO", precision = 22, scale = 0)
	public Double getPorComPromo() {
		return this.porComPromo;
	}

	/**
	 * @param porComPromo Double Comisión promocional
	 */
	public void setPorComPromo(Double porComPromo) {
		this.porComPromo = porComPromo;
	}

	/**
	 * @return String dscComPromo Descripcio de la comision
	 */
	@Column(name = "DSC_COM_PROMO", length = 100)
	public String getDscComPromo() {
		return this.dscComPromo;
	}

	/**
	 * @param dscComPromo String Describe si es por apertura o disposicion
	 */
	public void setDscComPromo(String dscComPromo) {
		this.dscComPromo = dscComPromo;
	}

	/**
	 * @return Long Número de LAPA
	 * 
	 */
	@Column(name = "NUM_LAPA", precision = 22, scale = 0)
	public Long getNumLapa() {
		return this.numLapa;
	}

	/**
	 * @param numLapa Long Número de LAPA
	 */
	public void setNumLapa(Long numLapa) {
		this.numLapa = numLapa;
	}

	/**
	 * @return txtNomTarjeta String Nombre de la tarjeta
	 */
	@Column(name = "TXT_NOM_TARJETA", length = 100)
	public String getTxtNomTarjeta() {
		return this.txtNomTarjeta;
	}

	/**
	 * @param txtNomTarjeta String Nombre de la tarjeta
	 */
	public void setTxtNomTarjeta(String txtNomTarjeta) {
		this.txtNomTarjeta = txtNomTarjeta;
	}

	/**
	 * @return String Numero de la tarjeta
	 */
	@Column(name = "TXT_NUM_TARJETA", length = 100)
	public String getTxtNumTarjeta() {
		return this.txtNumTarjeta;
	}

	/**
	 * @param txtNumTarjeta String Número de la tarjeta
	 */
	public void setTxtNumTarjeta(String txtNumTarjeta) {
		this.txtNumTarjeta = txtNumTarjeta;
	}

	/**
	 * @return Long Factor aseguro promocional
	 */
	@Column(name = "POR_FAC_ASEG_PROMO", precision = 22, scale = 0)
	public Long getPorFacAsegPromo() {
		return this.porFacAsegPromo;
	}

	/**
	 * @param porFacAsegPromo Long Factor aseguro promocional
	 */
	public void setPorFacAsegPromo(Long porFacAsegPromo) {
		this.porFacAsegPromo = porFacAsegPromo;
	}

	/**
	 * @return Long getCodVtaCcsIn Código de venta CCS In
	 */
	@Column(name = "COD_VTA_CCS_IN", precision = 22, scale = 0)
	public Long getCodVtaCcsIn() {
		return this.codVtaCcsIn;
	}

	/**
	 * @param codVtaCcsIn Long Código de venta CCS In
	 */
	public void setCodVtaCcsIn(Long codVtaCcsIn) {
		this.codVtaCcsIn = codVtaCcsIn;
	}

	/**
	 * @return Long codVtaCcsOut Código de venta CCS Out
	 */
	@Column(name = "COD_VTA_CCS_OUT", precision = 22, scale = 0)
	public Long getCodVtaCcsOut() {
		return this.codVtaCcsOut;
	}

	/**
	 * @param codVtaCcsOut Long Código de venta CCS Out
	 */
	public void setCodVtaCcsOut(Long codVtaCcsOut) {
		this.codVtaCcsOut = codVtaCcsOut;
	}

	/**
	 * @return Long codVtaRedIn Código de venta red IN
	 */
	@Column(name = "COD_VTA_RED_IN", precision = 22, scale = 0)
	public Long getCodVtaRedIn() {
		return this.codVtaRedIn;
	}

	/**
	 * @param codVtaRedIn Long Código de venta red IN
	 */
	public void setCodVtaRedIn(Long codVtaRedIn) {
		this.codVtaRedIn = codVtaRedIn;
	}

	/**
	 * @return Long codVtaRedOut Código de venta red OUT
	 */
	@Column(name = "COD_VTA_RED_OUT", precision = 22, scale = 0)
	public Long getCodVtaRedOut() {
		return this.codVtaRedOut;
	}

	/**
	 * @param codVtaRedOut Long Código de venta red OUT
	 */
	public void setCodVtaRedOut(Long codVtaRedOut) {
		this.codVtaRedOut = codVtaRedOut;
	}

	/**
	 * @return Long codVtaAsn Código de venta ASN
	 */
	@Column(name = "COD_VTA_ASN", precision = 22, scale = 0)
	public Long getCodVtaAsn() {
		return this.codVtaAsn;
	}

	/**
	 * @param codVtaAsn Long Código de venta ASN
	 */
	public void setCodVtaAsn(Long codVtaAsn) {
		this.codVtaAsn = codVtaAsn;
	}

	/**
	 * @return Long codVtaFve Código de venta FVE
	 */
	@Column(name = "COD_VTA_FVE", precision = 22, scale = 0)
	public Long getCodVtaFve() {
		return this.codVtaFve;
	}

	/**
	 * @param codVtaFve Long Código de venta FVE
	 */
	public void setCodVtaFve(Long codVtaFve) {
		this.codVtaFve = codVtaFve;
	}
	
	/**
	 * @return Long idPlanMandatorio Id del plan mandatorio
	 */
	@Column(name = "ID_PLN_MANDATORIO", precision = 22, scale = 0)
	public Long getIdPlanMandatorio() {
		return this.idPlanMandatorio;
	}
	
	
	/**
	 * @param idPlanMandatorio Long Id del plan mandatorio
	 */
	public void setIdPlanMandatorio(Long idPlanMandatorio) {
		this.idPlanMandatorio = idPlanMandatorio;
	}
}
