package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clase para manejar el catalogo de comisiones
 * Solo se usan dos. por apertura o por disposicion
 * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * SccMxMaeComision generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_COMISION")
public class SccMxMaeComision implements java.io.Serializable {

	/**
	 *  Identificador para serializar la clase
	 **/
	private static final long serialVersionUID = -538131651649249806L;
	/**
	 *  Identificador para la llave de la tabla Comisión 
	 **/
	private Long idComisionPk;
	/**
	 *  Descripción de la comisión 
	 **/
	private String dscComision;

	/**
	 * Constructor Vacio
	 */
	public SccMxMaeComision() {
	}


	/**
	 * Constructor para la comisión por id Comsion
	 * @param idComisionPk
	 * Id primary key
	 */
	public SccMxMaeComision(Long idComisionPk) {
		this.idComisionPk = idComisionPk;
	}

	/**
	 * Constructor sobre cargado con id y descripción de comisión
	 * @param idComisionPk
	 * Id comision primary
	 * @param dscComision
	 * Descripción
	 */
	public SccMxMaeComision(Long idComisionPk, String dscComision) {
		this.idComisionPk = idComisionPk;
		this.dscComision = dscComision;
	}

	/**
	 * @return Long idComisionPk
	 */
	@Id
	@Column(name = "ID_COMISION_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdComisionPk() {
		return this.idComisionPk;
	}

	/**
	 * @param idComisionPk Long
	 */
	public void setIdComisionPk(Long idComisionPk) {
		this.idComisionPk = idComisionPk;
	}

	/**
	 * @return String dscComision
	 */
	@Column(name = "DSC_COMISION", length = 100)
	public String getDscComision() {
		return this.dscComision;
	}

	/**
	 * @param dscComision String
	 */
	public void setDscComision(String dscComision) {
		this.dscComision = dscComision;
	}


}
