package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Campos de entidad
 * Entidad usada para obtener
 * datos de tabla de 
 * ofertas de campania
 * de la tabla
 * SCC_MX_MAE_OFER_CAM
 * 
 * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * 
 * SccMxMaeOferCam generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_OFER_CAM")
public class SccMxMaeOferCam implements IAbstractEntity, java.io.Serializable {


	/**
	 * serializacion de la entidad SccMxMaeOferCam
	 */
	private static final long serialVersionUID = -2184042609754126847L;
	/**
	 * Llave primaria de la oferta de campaña
	 */
	private Long idOferCamPk;
	/**
	 * Entidad para la periodicidad
	 */
	private SccMxMaePeriod sccMxMaePeriod;
	/**
	 * Entidad para el Producto
	 */
	private SccMxMaeProducto sccMxMaeProducto;
	/**
	 * Entidad para el segmento
	 */
	private SccMxMaeSegmento sccMxMaeSegmento;
	/**
	 * Llave foranea para identificar el subproducto de la campaña
	 */
	private Long idSubProd;
	/**
	 * Identificador del BUC de cliente
	 */
	private Long idBucClte;
	/**
	 * Fecha de Inicio de la promoción
	 */
	private Date fchIniProm;
	/**
	 * Fecha de Fin de la promoción
	 */
	private Date fchFinProm;
	/**
	 * Nombre completo del cliente
	 */
	private String descNombreCte;
	/**
	 * Numero de  cuenta del cliente al que aplica la promocion
	 */
	private Long numCuenta;
	/**
	 * Numero de credito anterior
	 */
	private Long numCredAnt;
	/**
	 * Numero de sucursal para la TDC anterior
	 */
	private Long numSucTdcAnt;
	/**
	 * Numero de contrato del credito anterior
	 */
	private Long numConTdcAnt;
	/**
	 * numero de lapa, aplica para LINEX
	 */
	private Long numLapa;
	/**
	 * Descripcion de la sucursal
	 */
	private String dscSucMnj;
	/**
	 * Clausulas para lectura
	 */
	private String txtLecClaus;
	/**
	 * Bandera que se combina con codvtaccsout para dar pase a contact center
	 */
	private Long codVtaCcsIn;
	/**
	 * Bandera que se combina con codvtaccsin para dar pase a contact center
	 */
	private Long codVtaCcsOut;
	/**
	 * Bandera que se combina con codvtaredout para dar pase a Sucursales
	 */
	private Long codVtaRedIn;
	/**
	 * Bandera que se combina con codvtaredin para dar pase a Sucursales
	 */
	private Long codVtaRedOut;
	/**
	 * Bandera que se combina con codvtafve para dar pase a fuerza de ventas
	 */
	private Long codVtaAsn;
	/**
	 * Bandera que se combina con codvtaasn para dar pase a fuerza de ventas
	 */
	private Long codVtaFve;
	/**
	 * Identificador del dia de pago
	 */
	private Long idDiaPagoFk;
	/**
	 * Codigo del calendario asociado
	 */
	private String codCalendario;

	/**
	 * Constructor super para la entidad:
	 * SccMxMaeOferCam
	 */
	public SccMxMaeOferCam() {
		super();
	}

	/**
	 * Constructor de las ofertas de campaña con información
	 * @param idOferCamPk
	 * Id primary key
	 * @param sccMxMaeProducto
	 * conexion con producto
	 * @param codSubProd
	 * Codigo del Subproducto relacionado, se usa en vez de la conexión con subproducto
	 * @param idBucClte
	 * buc del cliente
	 * @param fchFinProm
	 * fecha 
	 */
	public SccMxMaeOferCam(Long idOferCamPk, SccMxMaeProducto sccMxMaeProducto, Long codSubProd,
			Long idBucClte, Date fchFinProm) {
		this.idOferCamPk = idOferCamPk;
		this.sccMxMaeProducto = sccMxMaeProducto;
		this.idSubProd = idSubProd;
		this.idBucClte = idBucClte;
		this.fchFinProm = new Date(fchFinProm.getTime());
	}

	/**
	 * @return Long idOferCamPk Llave primaria de la tabla
	 */
	@Id
	@Column(name = "ID_OFER_CAM_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdOferCamPk() {
		return this.idOferCamPk;
	}

	/**
	 * @param idOferCamPk Llave primaria de la tabla
	 */
	public void setIdOferCamPk(Long idOferCamPk) {
		this.idOferCamPk = idOferCamPk;
	}

	/**
	 * @return SccMxMaePeriod Periodo
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERIOD_FK")
	public SccMxMaePeriod getSccMxMaePeriod() {
		return this.sccMxMaePeriod;
	}

	/**
	 * @param sccMxMaePeriod Periodo
	 */
	public void setSccMxMaePeriod(SccMxMaePeriod sccMxMaePeriod) {
		this.sccMxMaePeriod = sccMxMaePeriod;
	}

	/**
	 * @return SccMxMaeProducto Producto
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROD_FK", nullable = false)
	public SccMxMaeProducto getSccMxMaeProducto() {
		return this.sccMxMaeProducto;
	}

	/**
	 * @param sccMxMaeProducto Producto
	 */
	public void setSccMxMaeProducto(SccMxMaeProducto sccMxMaeProducto) {
		this.sccMxMaeProducto = sccMxMaeProducto;
	}

	/**
	 * @return SccMxMaeSegmento Segmento
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SEGMENTO_FK")
	public SccMxMaeSegmento getSccMxMaeSegmento() {
		return this.sccMxMaeSegmento;
	}

	/**
	 * @param sccMxMaeSegmento Segmento
	 */
	public void setSccMxMaeSegmento(SccMxMaeSegmento sccMxMaeSegmento) {
		this.sccMxMaeSegmento = sccMxMaeSegmento;
	}

	/**
	 * @param idSubProd Long Id de Subproducto
	 */
	public void setIdSubProd(Long idSubProd) {
		this.idSubProd = idSubProd;
	}

	/**
	 * @return Long idSubProd Id de Subproducto
	 */
	@Column(name = "ID_SUB_PROD_FK", nullable = false)
	public Long getIdSubProd() {
		return idSubProd;
	}

	/**
	 * @param idBucClte Long Clave del Cliente
	 */
	public void setIdBucClte(Long idBucClte) {
		this.idBucClte = idBucClte;
	}

	/**
	 * @return Long idBucClte Clave del Cliente
	 */
	@Column(name = "ID_BUC_CLTE", nullable = false, precision = 22, scale = 0)
	public Long getIdBucClte() {
		return this.idBucClte;
	}

	/**
	 * @param fchIniProm Date Fecha de inicio de la promocion
	 */
	public void setFchIniProm(Date fchIniProm) {
		this.fchIniProm = new Date(fchIniProm.getTime());
	}

	/**
	 * @return Date fchIniProm Fecha de inicio de la promocion
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FCH_INI_PROM", length = 11)
	public Date getFchIniProm() {
		return new Date(this.fchIniProm.getTime());
	}

	/**
	 * @param fchFinProm Date Fecha de fin de la promocion
	 */
	public void setFchFinProm(Date fchFinProm) {
		this.fchFinProm = new Date(fchFinProm.getTime());
	}

	/**
	 * @return Date fchFinProm Fecha de fin de la promocion
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FCH_FIN_PROM", nullable = false, length = 11)
	public Date getFchFinProm() {
		return new Date(this.fchFinProm.getTime());
	}

	/**
	 * @return String descNombreCte Nombre del cliente
	 */
	@Column(name = "DESC_NOMBRE_CTE", length = 100)
	public String getDescNombreCte() {
		return this.descNombreCte;
	}

	/**
	 * @param descNombreCte String Nombre del cliente
	 */
	public void setDescNombreCte(String descNombreCte) {
		this.descNombreCte = descNombreCte;
	}

	/**
	 * @return Long numCuenta Numero de cuenta
	 */
	@Column(name = "NUM_CUENTA", precision = 22, scale = 0)
	public Long getNumCuenta() {
		return this.numCuenta;
	}

	/**
	 * @param numCuenta Long Numero de cuenta
	 */
	public void setNumCuenta(Long numCuenta) {
		this.numCuenta = numCuenta;
	}

	/**
	 * @return Long numCredAnt Numero del credito anterior
	 */
	@Column(name = "NUM_CRED_ANT", precision = 22, scale = 0)
	public Long getNumCredAnt() {
		return this.numCredAnt;
	}

	/**
	 * @param numCredAnt Long Numero del credito anterior
	 */
	public void setNumCredAnt(Long numCredAnt) {
		this.numCredAnt = numCredAnt;
	}

	/**
	 * @return Long numSucTdcAnt Numero de sucursal TDC anterior
	 */
	@Column(name = "NUM_SUC_TDC_ANT", precision = 22, scale = 0)
	public Long getNumSucTdcAnt() {
		return this.numSucTdcAnt;
	}

	/**
	 * @param numSucTdcAnt Long Numero de sucursal TDC anterior
	 */
	public void setNumSucTdcAnt(Long numSucTdcAnt) {
		this.numSucTdcAnt = numSucTdcAnt;
	}

	/**
	 * @return Long numConTdcAnt Numero contrato TDC anterior
	 */ 
	@Column(name = "NUM_CON_TDC_ANT", precision = 22, scale = 0)
	public Long getNumConTdcAnt() {
		return this.numConTdcAnt;
	}

	/**
	 * @param numConTdcAnt Long Numero contrato TDC anterior
	 */
	public void setNumConTdcAnt(Long numConTdcAnt) {
		this.numConTdcAnt = numConTdcAnt;
	}

	/**
	 * @return Long numLapa Numero de LAPA
	 */
	@Column(name = "NUM_LAPA", precision = 22, scale = 0)
	public Long getNumLapa() {
		return this.numLapa;
	}

	/**
	 * @param numLapa Long Numero de LAPA
	 */
	public void setNumLapa(Long numLapa) {
		this.numLapa = numLapa;
	}

	/**
	 * @return String dscSucMnj Descripcion suc manejo
	 */
	@Column(name = "DSC_SUC_MNJ", length = 100)
	public String getDscSucMnj() {
		return this.dscSucMnj;
	}

	/**
	 * @param dscSucMnj String Descripcion suc manejo
	 */
	public void setDscSucMnj(String dscSucMnj) {
		this.dscSucMnj = dscSucMnj;
	}

	/**
	 * @return String txtLecClaus Texto Lec Claus
	 */
	@Column(name = "TXT_LEC_CLAUS", length = 100)
	public String getTxtLecClaus() {
		return this.txtLecClaus;
	}

	/**
	 * @param txtLecClaus String Texto Lec Claus
	 */
	public void setTxtLecClaus(String txtLecClaus) {
		this.txtLecClaus = txtLecClaus;
	}

	/**
	 * @return Long codVtaCcsIn Codigo Venta CCS In
	 */
	@Column(name = "COD_VTA_CCS_IN", precision = 22, scale = 0)
	public Long getCodVtaCcsIn() {
		return this.codVtaCcsIn;
	}

	/**
	 * @param codVtaCcsIn Long Codigo Venta CCS In
	 */
	public void setCodVtaCcsIn(Long codVtaCcsIn) {
		this.codVtaCcsIn = codVtaCcsIn;
	}

	/**
	 * @return Long codVtaCcsOut Codigo Venta CCS Out
	 */
	@Column(name = "COD_VTA_CCS_OUT", precision = 22, scale = 0)
	public Long getCodVtaCcsOut() {
		return this.codVtaCcsOut;
	}

	/**
	 * @param codVtaCcsOut Long Codigo Venta CCS Out
	 */
	public void setCodVtaCcsOut(Long codVtaCcsOut) {
		this.codVtaCcsOut = codVtaCcsOut;
	}

	/**
	 * @return Long codVtaRedIn Codigo Venta red In
	 */
	@Column(name = "COD_VTA_RED_IN", precision = 22, scale = 0)
	public Long getCodVtaRedIn() {
		return this.codVtaRedIn;
	}

	/**
	 * @param codVtaRedIn Long Codigo Venta red In
	 */
	public void setCodVtaRedIn(Long codVtaRedIn) {
		this.codVtaRedIn = codVtaRedIn;
	}

	/**
	 * @return Long codVtaRedOut Codigo Venta red Out
	 */
	@Column(name = "COD_VTA_RED_OUT", precision = 22, scale = 0)
	public Long getCodVtaRedOut() {
		return this.codVtaRedOut;
	}

	/**
	 * @param codVtaRedOut Long Codigo Venta red Out
	 */
	public void setCodVtaRedOut(Long codVtaRedOut) {
		this.codVtaRedOut = codVtaRedOut;
	}

	/**
	 * @return Long codVtaAsn Codigo Venta ASN
	 */
	@Column(name = "COD_VTA_ASN", precision = 22, scale = 0)
	public Long getCodVtaAsn() {
		return this.codVtaAsn;
	}

	/**
	 * @param codVtaAsn Long Codigo Venta ASN
	 */
	public void setCodVtaAsn(Long codVtaAsn) {
		this.codVtaAsn = codVtaAsn;
	}

	/**
	 * @return Long codVtaFve Codigo de venta FVE
	 */
	@Column(name = "COD_VTA_FVE", precision = 22, scale = 0)
	public Long getCodVtaFve() {
		return this.codVtaFve;
	}

	/**
	 * @param codVtaFve Long Codigo de venta FVE
	 */
	public void setCodVtaFve(Long codVtaFve) {
		this.codVtaFve = codVtaFve;
	}

	/**
	 * @return Long idDiaPagoFk Identificador del dia de pago (magisterio)
	 */
	@Column(name = "ID_DIA_PAGO_FK")
	public Long getIdDiaPagoFk() {
		return idDiaPagoFk;
	}

	/**
	 * @param Long idDiaPagoFk Identificador del dia de pago (magisterio)
	 */
	public void setIdDiaPagoFk(Long idDiaPagoFk) {
		this.idDiaPagoFk = idDiaPagoFk;
	}

	/**
	 * @return idCalendarioFk Identificador del calendario (magisterio)
	 */
	@Column(name = "COD_CALENDARIO")
	public String getCodCalendario() {
		return codCalendario;
	}

	/**
	 * @param idCalendarioFk Identificador del calendario (magisterio)
	 */
	public void setCodCalendario(String codCalendario) {
		this.codCalendario = codCalendario;
	}
}
