package mx.isban.scc.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/** 
 * Generado por GlobalHitss
 * Junio 2019
 * Sprint 3
 * Esta clase contiene el catalogo de archivos
 * son 11 tipos de archivo que pueden cargarse
 * desde la interfaz de carga de archivos
 * 
 * SccMxMaeTipoArch generated by hbm2java
 */
@Entity
@Table(name="SCC_MX_MAE_TIPO_ARCH")
public class SccMxMaeTipoArch implements java.io.Serializable{

	/**
	 * Identificador para serializar la clase
	 */
	private static final long serialVersionUID = -1874141859112810036L;
	
	@Id
	/**
	 * Identificador principal de la tabla tipo de archivo
	 */
	private Long idTipoArchPk;
	/**
	 * Descripcion del tipo de archivo 
	 */
	private String dscTipoArch;
	
	/**
	 * Constructor Vacio
	 */
	public SccMxMaeTipoArch() {
		
	}

	/**
	 * Constructor de tipo archivo
	 * @param idTipoArchPk
	 * llave
	 * @param dscTipoArch
	 * descripcion 
	 */
	public SccMxMaeTipoArch(Long idTipoArchPk, String dscTipoArch) {
		super();
		this.idTipoArchPk = idTipoArchPk;
		this.dscTipoArch = dscTipoArch;
	}

	/**
	 * @return Long idTipoArchPk
	 */
	public Long getIdTipoArchPk() {
		return idTipoArchPk;
	}

	/**
	 * @param idTipoArchPk Long
	 */
	public void setIdTipoArchPk(Long idTipoArchPk) {
		this.idTipoArchPk = idTipoArchPk;
	}

	/**
	 * @return String dscTipoArch
	 */
	public String getDscTipoArch() {
		return dscTipoArch;
	}

	/**
	 * @param dscTipoArch String
	 */
	public void setDscTipoArch(String dscTipoArch) {
		this.dscTipoArch = dscTipoArch;
	}
	
}
