package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clase para manejar la tabla de pago de seguro
 * que puede ser prima unica o recurrente
  * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * SccMxMaePagoSeguro generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_PAGO_SEGURO")
public class SccMxMaePagoSeguro implements java.io.Serializable {


	/**
	 * Identificador para serializar la clase
	 */
	private static final long serialVersionUID = 580938407064529054L;
	/**
	 * Llave principal para el pago de seguro
	 */
	private Long idPagSegPk;
	/**
	 * Descripcion del pago de seguro
	 */
	private String dscPagSeg;

	/**
	 * Constructor Vacio
	 */
	public SccMxMaePagoSeguro() {
	}

	/**
	 * Constructor con llave
	 * @param idPagSegPk
	 * llave
	 */
	public SccMxMaePagoSeguro(Long idPagSegPk) {
		this.idPagSegPk = idPagSegPk;
	}

	/**
	 * Constructor del pago de seguro por id y descripción
	 * @param idPagSegPk
	 * Primary key
	 * @param dscPagSeg
	 * descripción
	 */
	public SccMxMaePagoSeguro(Long idPagSegPk, String dscPagSeg) {
		this.idPagSegPk = idPagSegPk;
		this.dscPagSeg = dscPagSeg;
	}

	/**
	 * @return Long idPagSegPk
	 */
	@Id
	@Column(name = "ID_PAG_SEG_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdPagSegPk() {
		return this.idPagSegPk;
	}

	/**
	 * @param idPagSegPk Long
	 */
	public void setIdPagSegPk(Long idPagSegPk) {
		this.idPagSegPk = idPagSegPk;
	}

	/**
	 * @return String dscPagSeg
	 */
	@Column(name = "DSC_PAG_SEG", length = 100)
	public String getDscPagSeg() {
		return this.dscPagSeg;
	}

	/**
	 * @param dscPagSeg String
	 */
	public void setDscPagSeg(String dscPagSeg) {
		this.dscPagSeg = dscPagSeg;
	}

}
