package mx.isban.scc.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 *  Clase para dar seguimiento al catalogo de TIIE
 * Este catalogo es actualizado por un servicio de Santec
  * Generado por GlobalHitss
  * Fabrica de SOftware
  * para Proyecto Santander SImulador de Credito al consumo
 * Junio 2019
 * Sprint 2
 * SccMxMaeTiie generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_TIIE")
public class SccMxMaeTiie  implements IAbstractEntity, java.io.Serializable {

	/**
	 * Identificador para serializar la clase
	 */
	private static final long serialVersionUID = 4289233256506042520L;

	/**
	 * Propiedad idTasaTiiePk de la entidad SccMxMaeTiie 
	 * Llave primaria de la tabla
	 */
	private Long idTasaTiiePk;
	/**
	 * Propiedad tasaTiie de la entidad SccMxMaeTiie 
	 * Porcentaje de la tasa utilizado para PSG
	 */
	private Double porcTasaTiie;

	/**
	 * Propiedad tccEntit de la entidad SccMxMaeTiie
	 * Datos enviados de Santec
	 */
	private Long tccEntit;
	/**
	 * Propiedad coefici de la entidad SccMxMaeTiie
	 * Datos enviados de Santec
	 */
	private String coefici;
	/**
	 * Propiedad plazoIni de la entidad SccMxMaeTiie
	 * Datos enviados de Santec
	 */
	private Long plazoIni;
	/**
	 * Propiedad plazoFin de la entidad SccMxMaeTiie
	 * Datos enviados de Santec
	 */
	private Long plazoFin;
	/**
	 * Propiedad tcfechaIni de la entidad SccMxMaeTiie
	 * Datos enviados de Santec
	 */
	private Date tcfechaIni;
	/**
	 * Propiedad tcfechaFin de la entidad SccMxMaeTiie
	 * Datos enviados de Santec
	 */
	private Date tcfechaFin;
	/**
	 * Propiedad entidadUmo de la entidad SccMxMaeTiie
	 * Datos enviados de Santec
	 */
	private String entidadUmo;
	/**
	 * Propiedad centroUmo de la entidad SccMxMaeTiie
	 * Datos enviados de Santec
	 */
	private String centroUmo;
	/**
	 * Propiedad userIdUmo de la entidad SccMxMaeTiie
	 * Datos enviados de Santec
	 */
	private String userIdUmo;
	/**
	 * Propiedad netNameUmo de la entidad SccMxMaeTiie
	 * Datos enviados de Santec
	 */
	private String netNameUmo;
	/**
	 * Propiedad timeSetUmo de la entidad SccMxMaeTiie
	 * Datos enviados de Santec
	 */
	private Date timeSetUmo;
	
	
	
	
	
	
	/**
	 * constructor vacio
	 */
	public SccMxMaeTiie() {
		super();
	}

	
	/**
	 * Inician setters y getters
	 * @return idTasaTiiePk Id de la TIIE
	 * llave
	 */
	@Id
	@Column(name = "ID_TIIE_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdTasaTiiePk() {
		return idTasaTiiePk;
	}

	/**
	 * Se coloca el valor del ID la tasa TIIE
	 * @param idTasaTiiePk Id de la TIIE
	 */
	public void setIdTasaTiiePk(Long idTasaTiiePk) {
		this.idTasaTiiePk = idTasaTiiePk;
	}

	
	/**
	 * Obtiene el valor de la tasa TIIE
	 * @return porcTasaTiie Porcentaje de la TIIE
	 */
	@Column(name = "VALOR")
	public Double getPorcTasaTiie() {
		return porcTasaTiie;
	}

	
	/**
	 * Coloca el valor de la tasa TIIE
	 * @param porcTasaTiie Porcentaje de la TIIE
	 */
	public void setPorcTasaTiie(Double porcTasaTiie) {
		this.porcTasaTiie = porcTasaTiie;
	}


	/**Obtener txcc entidad
	 * @return tccEntit tccEntit
	 */
	@Column(name = "TCCENTIT")
	public Long getTccEntit() {
		return tccEntit;
	}


	/**
	 * Colocar tcc entidad
	 * @param tccEntit tccEntit
	 */
	public void setTccEntit(Long tccEntit) {
		this.tccEntit = tccEntit;
	}


	/**
	 * Obtener coeficiente
	 * @return coefici coeficiente
	 */
	@Column(name = "COEFICI")
	public String getCoefici() {
		return coefici;
	}


	/**
	 * Colocar coeficiente
	 * @param coefici coeficiente
	 */
	public void setCoefici(String coefici) {
		this.coefici = coefici;
	}


	/**
	 * Obtener plazo inicial
	 * @return plazoIni Plazo inicial
	 */
	@Column(name = "PLAZOINI")
	public Long getPlazoIni() {
		return plazoIni;
	}


	/**
	 * Colocar plazo inicial
	 * @param plazoIni Plazo inicial
	 */
	public void setPlazoIni(Long plazoIni) {
		this.plazoIni = plazoIni;
	}


	/**
	 * Obtener fecha inicio
	 * @return tcfechaIni TC Fecha Inicial
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TCFECHIN")
	public Date getTcfechaIni() {
		return new Date(this.tcfechaIni.getTime());
	}


	/**
	 * Colocar fecha inicio
	 * @param tcfechaIni TC Fecha Inicial
	 */
	public void setTcfechaIni(Date tcfechaIni) {
		this.tcfechaIni =  new Date(tcfechaIni.getTime());
	}


	/**obtener fecha fin
	 * @return tcfechaFin TC Fecha Final
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TCFECHFI")
	public Date getTcfechaFin() {
		return new Date(this.tcfechaFin.getTime());
	}


	/**
	 * colocar fecha fin
	 * @param tcfechaFin TC Fecha Final
	 */
	public void setTcfechaFin(Date tcfechaFin) {
		this.tcfechaFin = new Date(tcfechaFin.getTime());
	}


	/**
	 * Obtener entidad umo
	 * @return entidadUmo Entidad UMO
	 */
	@Column(name = "ENTIDAD_UMO")
	public String getEntidadUmo() {
		return entidadUmo;
	}


	/**
	 * Colocar entidad umo
	 * @param entidadUmo Entidad UMO
	 */
	public void setEntidadUmo(String entidadUmo) {
		this.entidadUmo = entidadUmo;
	}


	/**
	 * obtener centro umo
	 * @return centroUmo Centro UMO
	 */
	@Column(name = "CENTRO_UMO")
	public String getCentroUmo() {
		return centroUmo;
	}


	/**
	 * Colocar centro umo
	 * @param centroUmo Centro UMO
	 */
	public void setCentroUmo(String centroUmo) {
		this.centroUmo = centroUmo;
	}


	/**
	 * obtener user id umo
	 * @return userIdUmo User Id UMO
	 */
	@Column(name = "USERID_UMO")
	public String getUserIdUmo() {
		return userIdUmo;
	}


	/**
	 * Colocar User Id umo
	 * @param userIdUmo User Id UMO
	 */
	public void setUserIdUmo(String userIdUmo) {
		this.userIdUmo = userIdUmo;
	}


	/**
	 * Obterner name umo
	 * @return netNameUmo Net Name UMO
	 */
	@Column(name = "NETNAME_UMO")
	public String getNetNameUmo() {
		return netNameUmo;
	}


	/**
	 * Colocar Name Umo
	 * @param netNameUmo Net Name UMO
	 */
	public void setNetNameUmo(String netNameUmo) {
		this.netNameUmo = netNameUmo;
	}


	/**
	 * Obtener Time Set UMO
	 * @return timeSetUmo Time set UMO
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESET_UMO")
	public Date getTimeSetUmo() {
		return new Date(this.timeSetUmo.getTime());
	}


	/**
	 * Colocar time set UMO
	 * @param timeSetUmo Time set UMO
	 */
	public void setTimeSetUmo(Date timeSetUmo) {
		this.timeSetUmo = new Date(timeSetUmo.getTime());
	}


	/**
	 * Obtener plazo fin
	 * @return plazoFin Plazo Fin
	 */
	@Column(name = "PLAZOFIN")
	public Long getPlazoFin() {
		return plazoFin;
	}


	/**
	 * Colocar plazo fin
	 * @param plazoFin Plazo Fin
	 */
	public void setPlazoFin(Long plazoFin) {
		this.plazoFin = plazoFin;
	}
	
}
