package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clase para manejar la informacion de CARTERA
 * la cual indica el saldo de creditos existentes
 * en caso de que apliquen para restituir.
 * La restitucion se permite siempre que el codigo de producto este
 * vigente de acuerdo a lo indicado por la tabla tipoCartera
 * Generado por GlobalHitss
 * Fabrica de Software
 * Para Simulador de Credito al Consumo
 * Cliente Santander
 * Mayo 2019
 * Sprint 1
 * SccMxMaeAppCartera generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_APP_CARTERA")
public class SccMxMaeAppCartera implements IAbstractEntity, java.io.Serializable {

	/**
	 * serializacion de la entidad SccMxMaeAppCartera
	 */
	private static final long serialVersionUID = -2695892048848792873L;
	/**
	 * propiedad idCdto de la entidad SccMxMaeAppCartera
	 */
	private Long idCdto;
	/**
	 * Relacion con el Producto, por medio de su codigo
	 */
	private Long codigoProducto;
	/**
	 * Numero de cliente o BUC para relacionarlo con campañas
	 */
	private Long numClte;
	/**
	 * Numero de Credito para relacionarlo con campaña
	 */
	private Long numCdto;
	/**
	 * Nombre del Cliente, tambien se ocupa si el buc se busca en el simulador y 
	 * no se encuentra en campaña
	 */
	private String txtNomClte;
	/**
	 *  Numero de meses del plazo del seguro
	 */
	private Long numPlazo;
	/**
	 * Identifica la periodicidad de pagos para este credito
	 */
	private Long numPrdoPagos;
	/**
	 * Porcentaje de la tasa de interes
	 */
	private Double numTasaInt;
	/**
	 * Valor total del adeudo del credito
	 */
	private Double numDeudaTotal;
	/**
	 * Valor del seguro adquirido con el credito
	 */
	private Double numMontoSeg;
	/**
	 *Fecha de adquisicion del seguro
	 */
	private Date fchFormal;

	/**
	 * Constructor Vacio
	 */
	public SccMxMaeAppCartera() {
	}

	/**
	 * Constructor para la tabla de Cartera
	 * @param idCdto
	 * Id de tabla
	 * @param codigoProducto
	 * Registro del código del producto
	 * @param numClte
	 * Numero de cliente
	 * @param numCdto
	 * Numero de credito
	 */
	public SccMxMaeAppCartera(Long idCdto, Long codigoProducto, Long numClte, Long numCdto) {
		this.idCdto = idCdto;
		this.codigoProducto = codigoProducto;
		this.numClte = numClte;
		this.numCdto = numCdto;
	}

	@Id

	@Column(name = "ID_CDTO", unique = true, nullable = false, precision = 22, scale = 0)
	/**
	 * Inician setters y getters
	 * @return id de credito
	 */
	public Long getIdCdto() {
		return this.idCdto;
	}

	/**
	 * 
	 * @param idCdto
	 * Id del credito
	 */
	public void setIdCdto(Long idCdto) {
		this.idCdto = idCdto;
	}

	@Column(name = "COD_PROD", nullable = false, precision = 22, scale = 0)
	/**
	 * Get el código del  producto
	 * @return el código del producto
	 */
	public Long getCodigoProducto() {
		return codigoProducto;
	}

	/**
	 * Setea el objeto que conecta con la tabla de producto
	 * @param codigoProducto
	 * Código del  producto
	 */
	public void setCodigoProducto(Long codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	@Column(name = "NUM_CLTE", nullable = false, precision = 22, scale = 0)
	/**
	 * Obtiene el numero de cliente
	 * @return numClte Número de cliente (BUC) 
	 * que es el num de cliente
	 */
	public Long getNumClte() {
		return this.numClte;
	}

	/**
	 * Setea el buc
	 * @param numClte
	 * Buc del cliente
	 */
	public void setNumClte(Long numClte) {
		this.numClte = numClte;
	}

	@Column(name = "NUM_CDTO", nullable = false, precision = 22, scale = 0)
	/**
	 * Obtiene numero de credito 
	 * @return numCdto
	 * 
	 */
	public Long getNumCdto() {
		return this.numCdto;
	}

	/**
	 * Setter para numCdto
	 * @param numCdto
	 * Setea el numero del credito
	 */
	public void setNumCdto(Long numCdto) {
		this.numCdto = numCdto;
	}

	@Column(name = "TXT_NOM_CLTE", length = 100)
	/**
	 * Obtiene el nombre del cliente
	 * @return txtNomClte
	 * idem
	 */
	public String getTxtNomClte() {
		return this.txtNomClte;
	}

	/**
	 * Setea el nombre del cliente
	 * @param txtNomClte
	 * lo dicho
	 */
	public void setTxtNomClte(String txtNomClte) {
		this.txtNomClte = txtNomClte;
	}

	/**
	 * @return numPlazo Número de plazos del crédito
	 */
	@Column(name = "NUM_PLAZO", precision = 22, scale = 0)
	public Long getNumPlazo() {
		return this.numPlazo;
	}

	/**
	 * Setea el numero de plazos
	 * @param numPlazo Número de plazos del crédito
	 */
	public void setNumPlazo(Long numPlazo) {
		this.numPlazo = numPlazo;
	}

	/**
	 * @return numPrdoPagos Número de pagos por periodo
	 */
	@Column(name = "NUM_PRDO_PAGOS", precision = 22, scale = 0)
	public Long getNumPrdoPagos() {
		return this.numPrdoPagos;
	}

	/**
	 * Setea el numero de pagos por periodo
	 * @param numPrdoPagos Número de pagos por periodo
	 */
	public void setNumPrdoPagos(Long numPrdoPagos) {
		this.numPrdoPagos = numPrdoPagos;
	}

	/**
	 * @return numTasaInt Tasa interés
	 */
	@Column(name = "NUM_TASA_INT", precision = 22, scale = 2)
	public Double getNumTasaInt() {
		return this.numTasaInt;
	}

	/**
	 * Setea la tasa de interes
	 * @param numTasaInt Tasa interés
	 */
	public void setNumTasaInt(Double numTasaInt) {
		this.numTasaInt = numTasaInt;
	}

	/**
	 * @return numDeudaTotal Deuda Total
	 */
	@Column(name = "NUM_DEUDA_TOTAL", precision = 22, scale = 2)
	public Double getNumDeudaTotal() {
		return this.numDeudaTotal;
	}

	/**
	 * @param numDeudaTotal  Deuda Total
	 */
	public void setNumDeudaTotal(Double numDeudaTotal) {
		this.numDeudaTotal = numDeudaTotal;
	}

	/**
	 * @return numMontoSeg Monto del seguro
	 */
	@Column(name = "NUM_MONTO_SEG", precision = 22, scale = 2)
	public Double getNumMontoSeg() {
		return this.numMontoSeg;
	}

	/**
	 * @param numMontoSeg Monto del seguro
	 */
	public void setNumMontoSeg(Double numMontoSeg) {
		this.numMontoSeg = numMontoSeg;
	}

	/**
	 * @return fchFormal Fecha de formalización del crédito
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FCH_FORMAL", length = 11)
	public Date getFchFormal() {
		return new Date(this.fchFormal.getTime());
	}

	/**
	 * @param fchFormal Fecha de formalización del crédito
	 */
	public void setFchFormal(Date fchFormal) {
		this.fchFormal = new Date(fchFormal.getTime());
	}

}
