package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 
  * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * SccMxMaeApartados generated by hbm2java
 * Un Apartado es una seccion en la pantalla de simulacion, 
 * se refiere al apartado de Oferta Actual, Oferta Promocional
 * conversion Auto y Ahorro
 */
@Entity
@Table(name = "SCC_MX_MAE_APARTADOS")
public class SccMxMaeApartados implements java.io.Serializable {

	
	/**
	 * Serializador de la clase
	 */
	private static final long serialVersionUID = 7358665411188412953L;
	/**
	 * llave primaria para los apartados
	 */
	private Long idApartadoPk;
	/**
	 * Descripción del apartado
	 */
	private String dscApartado;

	/**
	 * Constructor Vacio
	 */
	public SccMxMaeApartados() {
	}

	/**
	 * Constructor para la tabla de apartados
	 * @param idApartadoPk
	 * Id primary key
	 */
	public SccMxMaeApartados(Long idApartadoPk) {
		this.idApartadoPk = idApartadoPk;
	}

	/**
	 * Segundo constructor
	 * @param idApartadoPk
	 * llave
	 * @param dscApartado
	 * Descripcion
	 */
	public SccMxMaeApartados(Long idApartadoPk, String dscApartado) {
		this.idApartadoPk = idApartadoPk;
		this.dscApartado = dscApartado;
	}

	/**
	 * @return Long idApartadoPk
	 */
	@Id
	@Column(name = "ID_APARTADO_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdApartadoPk() {
		return this.idApartadoPk;
	}

	/**
	 * @param idApartadoPk Long
	 */
	public void setIdApartadoPk(Long idApartadoPk) {
		this.idApartadoPk = idApartadoPk;
	}

	/**
	 * @return String dscApartado
	 */
	@Column(name = "DSC_APARTADO", length = 100)
	public String getDscApartado() {
		return this.dscApartado;
	}

	/**
	 * @param dscApartado String
	 */
	public void setDscApartado(String dscApartado) {
		this.dscApartado = dscApartado;
	}


}
