package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clase para manejar el catalogo de modalidades
 * que indica si es campania, mercado abierto , ambos o ninguno
  * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * SccMxMaeModalidad generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_MODALIDAD")
public class SccMxMaeModalidad implements java.io.Serializable {

	/**
	 *  Identificador para serializar la clase 
	 **/
	private static final long serialVersionUID = -8167749365468655122L;
	/**
	 *  Llave primaria de modalidad 
	 **/
	private Long idModalidadPk;
	/**
	 *  Descripción de modalidad 
	 **/
	private String dscModalidad;

	/**
	 * Constructor Vacio
	 */
	public SccMxMaeModalidad() {
	}

	/**
	 * Constructor de modalidad por id
	 * @param idModalidadPk
	 * primary key
	 */
	public SccMxMaeModalidad(Long idModalidadPk) {
		this.idModalidadPk = idModalidadPk;
	}

	/**
	 * Constructor sobre cargado con id y descripción
	 * @param idModalidadPk
	 * Primary key
	 * @param dscModalidad
	 * descripcion
	 */
	public SccMxMaeModalidad(Long idModalidadPk, String dscModalidad) {
		this.idModalidadPk = idModalidadPk;
		this.dscModalidad = dscModalidad;
	}

	/**
	 * @return Long idModalidadPk
	 */
	@Id
	@Column(name = "ID_MODALIDAD_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdModalidadPk() {
		return this.idModalidadPk;
	}

	/**
	 * @param idModalidadPk Long
	 */
	public void setIdModalidadPk(Long idModalidadPk) {
		this.idModalidadPk = idModalidadPk;
	}

	/**
	 * @return String dscModalidad
	 */
	@Column(name = "DSC_MODALIDAD", length = 100)
	public String getDscModalidad() {
		return this.dscModalidad;
	}

	/**
	 * @param dscModalidad String
	 */
	public void setDscModalidad(String dscModalidad) {
		this.dscModalidad = dscModalidad;
	}


}
