package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 
 * Generado por GlobalHitss
 * Fabrica de Software
 * Para Simulador de Credito al Consumo
 * Cliente Santander
 * Mayo 2019
 * Sprint 1
 * SccMxMaeTipoCartera generated by hbm2java
 * Esta clase espejea la entidad scc_mx_Mae_tipo_cartera
 * Con esta entidad se identifican aquellos tipos de producto
 * que van a ser visibles en la cartera de clientes. El usuario indica con 1 o 0 en la bandera
 * si el crédito es visible o no para el simulador
 * La cartera identifica a aquellos créditos que se encuentran vigentes
 * y que pueden ser restituidos por otro crédito nuevo en el simulador
 */
@Entity
@Table(name = "SCC_MX_MAE_TIPO_CARTERA")
public class SccMxMaeTipoCartera implements IAbstractEntity, java.io.Serializable {

	/**
	 * serializacion de la entidad SccMxMaeTipoCartera
	 */
	private static final long serialVersionUID = -2695892048848792873L;
	/**
	 * propiedad codProd de la entidad SccMxMaeTipoCartera
	 * Indica qué codigo de producto será visible al simulador
	 */
	private Long codProd;
	/**
	 * propiedad flgCartera de la entidad SccMxMaeTipoCartera.
	 * Indica con 1 que es visible al simulador
	 * con  0 no es visible
	 */
	private Long flgCartera;

	/**
	 * Constructor Vacio
	 */
	public SccMxMaeTipoCartera() {
	}

	/**
	 * Constructor para la tabla de Cartera
	 * @param codProd
	 * codigo producto que es visible al simulador
	 * @param flgCartera
	 * parametro para indicar visibilidad (1 = visible)
	 */
	public SccMxMaeTipoCartera(Long codProd, Long flgCartera) {
		this.codProd = codProd;
		this.flgCartera = flgCartera;
	}

	@Id

	@Column(name = "COD_PROD", unique = true, nullable = false, precision = 22, scale = 0)
	/**
	 * Inician setters y getters
	 * @return codProd Código del producto
	 */
	public Long getCodProd() {
		return this.codProd;
	}

	/**
	 * 
	 * @param codProd Código del producto
	 */
	public void setCodProd(Long codProd) {
		this.codProd = codProd;
	}

	@Column(name = "FLG_CARTERA", nullable = false, precision = 22, scale = 0)
	/**
	 * @return flgCartera Indicador de cartera
	 */
	public Long getFlgCartera() {
		return flgCartera;
	}

	/**
	 * @param flgCartera Indicador de cartera
	 */
	public void setFlgCartera(Long flgCartera) {
		this.flgCartera = flgCartera;
	}
}
