package mx.isban.scc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * 
 * * Generado por GlobalHitss Mayo 2019 Sprint 1
 * 
 * 
 * SccMxMaeProducto generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_PLANT_TIPO_PROD")
public class SccMxMaePlantTipoProd implements IAbstractEntity, java.io.Serializable {

	/**
	 * Serializacion de la clase
	 */
	private static final long serialVersionUID = 4179257326528707148L;
	/**
	 * Llave principal para tabla producto
	 */
	private Long idPlantTipoProdPk;
	/**
	 * Conexion con tabla de tipo de plantilla
	 */
	private SccMxMaeTipoPlantilla tipoPlantillaFk;
	/**
	 * Bytes de la plantilla
	 */
	private byte[] plantilla;


	@Id
	@Column(name = "ID_PLANT_TIPO_PROD", unique = true, nullable = false, precision = 22, scale = 0)
	/**
	 * getter de id
	 * 
	 * @return la llave de la tabla
	 */
	public Long getIdPlantTipoProdPk() {
		return idPlantTipoProdPk;
	}

	/**
	 * Setter de id
	 * 	identifica la plantilla con el numero que
	 * el usuario haya escrito en la tabla de campaña
	 * @return idPlantilla
	 * Con este identificador consigue como tal cuál de todos los certificados
	 * o carta compromiso o cuál documento se requiere 
	 *
	 * @param idPlantTipoProdPk la llave de la tabla
	 */
	public void setIdPlantTipoProdPk(Long idPlantTipoProdPk) {
		this.idPlantTipoProdPk = idPlantTipoProdPk;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_TIPO_PLANTILLA_FK")

	/**
	 * Getter del tipo de plantilla
	 * 
	 * @return SccMxMaeTipoPlantilla el tipo de cplantilla
	 */
	public SccMxMaeTipoPlantilla getTipoPlantillaFk() {
		return tipoPlantillaFk;
	}

	/**
	 * setter del tipo de plantilla
	 * 1 = Carta Compromiso, 2 = CD, 3 = MF, 4 = Mandatorio -este no se ocupa-
	 * @param tipoPlantillaFk tabla de amortizacion
	 */
	public void setTipoPlantillaFk(SccMxMaeTipoPlantilla tipoPlantillaFk) {
		this.tipoPlantillaFk = tipoPlantillaFk;
	}

	@Lob
	@Column(name = "DSC_PLANTILLA")
	/**
	 * getter de la plantilla
	 * 
	 * @return bytes con los datos de la plantilla
	 */
	public byte[] getPlantilla() {
		return plantilla.clone();
	}

	/**
	 * setter para la plantilla
	 * 
	 * @param plantilla byte array con los datos de la plantilla
	 */
	public void setPlantilla(byte[] plantilla) {
		this.plantilla = plantilla.clone();
	}



}
