package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Clase relacionada con el catalogo de subproductos
 * este catalogo se carga con los shells de CRM
 * Generado por GlobalHitss
 * Fabrica de Software
 * Para simulador Santander
 * Mayo 2019
 * Sprint 1
 * 
 * SccMxMaeSubProd generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_SUB_PROD")
public class SccMxMaeSubProd implements IAbstractEntity, java.io.Serializable {


	/** 
	 * Serializador de la clase
	 */
	private static final long serialVersionUID = -4083234298703461988L;
	/**
	 * Llave primaria de subproducto
	 */
	private Long idSubProdPk;
	/**
	 * Registro de conexion con tabla de producto
	 */
	private SccMxMaeProducto sccMxMaeProducto;
	/**
	 * Codigo de subproducto
	 */
	private Long codSubProd;
	/**
	 * Nombre de subproducto
	 */
	private String dscNombre;
	

	public SccMxMaeSubProd() {
	}

	/**
	 * Constructor mini
	 * @param idSubProdPk
	 * Llave
	 * @param sccMxMaeProducto
	 * Objeto de producto
	 */
	public SccMxMaeSubProd(Long idSubProdPk, SccMxMaeProducto sccMxMaeProducto) {
		this.idSubProdPk = idSubProdPk;
		this.sccMxMaeProducto = sccMxMaeProducto;
	}

	/**
	 * Constructor para la tabla maestra de subproducto con todos sus datos
	 * @param idSubProdPk
	 * primary key
	 * 
	 * @param sccMxMaeProducto
	 * Conexion con producto
	 * @param codSubProd
	 * codigo de subproducto
	 * @param dscNombre
	 * descripcion s
	 */
	public SccMxMaeSubProd(Long idSubProdPk, SccMxMaeProducto sccMxMaeProducto, Long codSubProd, String dscNombre) {
		this.idSubProdPk = idSubProdPk;
		this.sccMxMaeProducto = sccMxMaeProducto;
		this.codSubProd = codSubProd;
		this.dscNombre = dscNombre;
		
	}

	/**
	 * @return Long idSubProdPk
	 */
	@Id
	@Column(name = "ID_SUB_PROD_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdSubProdPk() {
		return this.idSubProdPk;
	}

	/**
	 * @param idSubProdPk Long
	 */
	public void setIdSubProdPk(Long idSubProdPk) {
		this.idSubProdPk = idSubProdPk;
	}
	
	
	/**
	 * @return SccMxMaeProducto sccMxMaeProducto
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_PROD_FK", nullable = false)
	public SccMxMaeProducto getSccMxMaeProducto() {
		return this.sccMxMaeProducto;
	}

	/**
	 * @param sccMxMaeProducto SccMxMaeProducto
	 */
	public void setSccMxMaeProducto(SccMxMaeProducto sccMxMaeProducto) {
		this.sccMxMaeProducto = sccMxMaeProducto;
	}

	/**
	 * @return Long codSubProd
	 */
	@Column(name = "COD_SUB_PROD")
	public Long getCodSubProd() {
		return this.codSubProd;
	}

	/**
	 * @param codSubProd Long
	 */
	public void setCodSubProd(Long codSubProd) {
		this.codSubProd = codSubProd;
	}

	/**
	 * @return String dscNombre
	 */
	@Column(name = "DSC_NOMBRE", length = 100)
	public String getDscNombre() {
		return this.dscNombre;
	}

	/**
	 * @param dscNombre String
	 */
	public void setDscNombre(String dscNombre) {
		this.dscNombre = dscNombre;
	}

	

}
