package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clase para manejar el catalogo 
 * de amortizaciones por plan frances(1) o aleman(2)
 *  * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * 
 * 
 * SccMxMaeAmortiz generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_AMORTIZ")
public class SccMxMaeAmortiz implements java.io.Serializable {

	/**
	 *  Identificador para serializar la clase
	 **/
	private static final long serialVersionUID = 3344188648617258917L;
	/**
	 *  Identificador del primary key para las amortizaciones 
	 **/
	private Long idAmortizPk;
	/**
	 *  Descripcion del tipo de amortización 
	 **/
	private String dscAmortiz;

	/**
	 * Constructor Vacio
	 */
	public SccMxMaeAmortiz() {
	}

	/** 
	 * Constructor de la tabla de amortización
	 * @param idAmortizPk
	 * Id
	 * @param dscAmortiz
	 * Descripción
	 */
	public SccMxMaeAmortiz(Long idAmortizPk, String dscAmortiz) {
		this.idAmortizPk = idAmortizPk;
		this.dscAmortiz = dscAmortiz;
	}


	/**
	 * @return Long idAmortizPk
	 */
	@Id
	@Column(name = "ID_AMORTIZ_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdAmortizPk() {
		return this.idAmortizPk;
	}

	/**
	 * @param idAmortizPk Long
	 */ 
	public void setIdAmortizPk(Long idAmortizPk) {
		this.idAmortizPk = idAmortizPk;
	}

	/**
	 * @return String dscAmortiz
	 */
	@Column(name = "DSC_AMORTIZ", nullable = false, length = 100)
	public String getDscAmortiz() {
		return this.dscAmortiz;
	}

	/**
	 * @param dscAmortiz String
	 */
	public void setDscAmortiz(String dscAmortiz) {
		this.dscAmortiz = dscAmortiz;
	}

}
