package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/** 
 * Clase para relacionar con la tabla 
 * de tipo de consumo: Nomina, Efectivo o LInex
 * Generado por GlobalHitss
 * Mayo 2019
 * Sprint 1
 * 
 * SccMxMaeTipoConsumo generated by hbm2java
 * @author Hitss
 */
@Entity
@Table(name = "SCC_MX_MAE_TIPO_CONSUMO")
public class SccMxMaeTipoConsumo implements java.io.Serializable {


	/**
	 * Serializador para la clase
	 */
	private static final long serialVersionUID = -1623941365331854999L;
	/**
	 * Llave primaria tipo consumo
	 */
	private Long idTipoConsumoPk;
	/**
	 * Descripción de tipo de consumo
	 */
	private String dscTipoConsumo;

	/**
	 * Constructor Vacio
	 */
	public SccMxMaeTipoConsumo() {
	}

	/**
	 * Constructor de tipo de consumo por llave
	 * @param idTipoConsumoPk
	 * llave
	 */
	public SccMxMaeTipoConsumo(Long idTipoConsumoPk) {
		this.idTipoConsumoPk = idTipoConsumoPk;
	}

	/**
	 * Constructor completo
	 * @param idTipoConsumoPk
	 * id primary key
	 * @param dscTipoConsumo
	 * descripcion
	 */
	public SccMxMaeTipoConsumo(Long idTipoConsumoPk, String dscTipoConsumo) {
		this.idTipoConsumoPk = idTipoConsumoPk;
		this.dscTipoConsumo = dscTipoConsumo;
	}

	/**
	 * @return Long idTipoConsumoPk
	 */
	@Id
	@Column(name = "ID_TIPO_CONSUMO_PK", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdTipoConsumoPk() {
		return this.idTipoConsumoPk;
	}

	/**
	 * @param idTipoConsumoPk Long
	 */
	public void setIdTipoConsumoPk(Long idTipoConsumoPk) {
		this.idTipoConsumoPk = idTipoConsumoPk;
	}

	/**
	 * @return String dscTipoConsumo
	 */
	@Column(name = "DSC_TIPO_CONSUMO", length = 100)
	public String getDscTipoConsumo() {
		return this.dscTipoConsumo;
	}

	/**
	 * @param dscTipoConsumo String
	 */
	public void setDscTipoConsumo(String dscTipoConsumo) {
		this.dscTipoConsumo = dscTipoConsumo;
	}


}
