	package mx.isban.scc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * 
 * * Generado por GlobalHitss Mayo 2019 Sprint 1
 * 
 * 
 * SccMxMaeProducto generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_PLANT_TA")
public class SccMxMaePlantTA implements IAbstractEntity, java.io.Serializable {

	/**
	 * Serializacion de la clase
	 */
	private static final long serialVersionUID = -5973030121130120519L;
	/**
	 * Llave principal para tabla producto
	 */
	private Long idPlantTaPk;
	/**
	 * Conexion con tabla de tipo de plantilla
	 */
	private SccMxMaeTipoPlantilla tipoPlantillaFk;
	/**
	 * Bytes de la plantilla
	 */
	private byte[] plantilla;

	@Id
	@Column(name = "ID_SCC_MX_MAE_PLANT_TA_PK", unique = true, nullable = false, precision = 22, scale = 0)
	/**
	 * getter de id
	 * 
	 * @return la llave de la tabla
	 */
	public Long getIdPlantTaPk() {
		return idPlantTaPk;
	}

	/**
	 * Setter de id
	 * 
	 * @param idPlantTaPk la llave de la tabla
	 */
	public void setIdPlantTaPk(Long idPlantTaPk) {
		this.idPlantTaPk = idPlantTaPk;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_TIPO_PLANTILLA_FK")

	/**
	 * Getter del tipo de plantilla
	 * 
	 * @return SccMxMaeTipoPlantilla el tipo de cplantilla
	 */
	public SccMxMaeTipoPlantilla getTipoPlantillaFk() {
		return tipoPlantillaFk;
	}

	/**
	 * setter del tipo de plantilla
	 * 
	 * @param tipoPlantillaFk tabla de amortizacion
	 */
	public void setTipoPlantillaFk(SccMxMaeTipoPlantilla tipoPlantillaFk) {
		this.tipoPlantillaFk = tipoPlantillaFk;
	}

	@Lob
	@Column(name = "DSC_PLANTILLA")
	/**
	 * getter de la plantilla
	 * 
	 * @return bytes con los datos de la plantilla
	 */
	public byte[] getPlantilla() {
		return plantilla.clone();
	}

	/**
	 * setter para la plantilla
	 * 
	 * @param plantilla byte array con los datos de la plantilla
	 */
	public void setPlantilla(byte[] plantilla) {
		this.plantilla = plantilla.clone();
	}

}
