package mx.isban.scc.model;
// Generated 26/04/2019 10:00:38 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clase para manejar el catalogo de fondos de garantia
 * solo se ocupa en personal select garantia
  * Generado por GlobalHitss
  * Fabrica de SOftware
  * para Proyecto Santander SImulador de Credito al consumo
 * Mayo 2019
 * Sprint 1
 * SccMxMaeFondoGarId generated by hbm2java
 */
@Entity
@Table(name = "SCC_MX_MAE_FONDO_GAR")
public class SccMxMaeFondoGarId implements IAbstractEntity, java.io.Serializable {

	/**
	 *  Identificador para serializar la clase 
	 **/
	private static final long serialVersionUID = 8702362698754910716L;
	/**
	 *  Identificador para la llave primaria de fondo de garantía 
	 **/
	private Long idFondGarPk;
	/**
	 *  Descripcion de fondo de garantía 
	 **/
	private String dscFondGar;
	/**
	 *  Porcentaje de comisión de fondo de garantía
	 **/
	private Double porComFondGar;

	/**
	 * Constructor Vacio
	 */
	public SccMxMaeFondoGarId() {
	}

	/**
	 * Constructor de Fondo de Garantía por id 
	 * @param idFondGarPk Id del fondo de garantía
	 * Primary key
	 */
	public SccMxMaeFondoGarId(Long idFondGarPk) {
		this.idFondGarPk = idFondGarPk;
	}

	/**
	 * Constructor de fondo de garantia por id, descripción y comisión
	 * @param idFondGarPk
	 * Primary key
	 * @param dscFondGar
	 * Descripción
	 * @param porComFondGar
	 * Porcentaje de la comisión
	 */
	public SccMxMaeFondoGarId(Long idFondGarPk, String dscFondGar, Double porComFondGar) {
		this.idFondGarPk = idFondGarPk;
		this.dscFondGar = dscFondGar;
		this.porComFondGar = porComFondGar;
	}

	/**
	 * @return idFondGarPk Id del fondo de garantía
	 */
	@Id
	@Column(name = "ID_FOND_GAR_PK", nullable = false, precision = 22, scale = 0)
	public Long getIdFondGarPk() {
		return this.idFondGarPk;
	}

	/**
	 * @param idFondGarPk Id del fondo de garantía
	 */
	public void setIdFondGarPk(Long idFondGarPk) {
		this.idFondGarPk = idFondGarPk;
	}

	/** 
	 * @return dscFondGar Descripción del fondo de garantía
	 */
	@Column(name = "DSC_FOND_GAR", length = 100)
	public String getDscFondGar() {
		return this.dscFondGar;
	}

	/**
	 * @param dscFondGar Descripción del fondo de garantía
	 */
	public void setDscFondGar(String dscFondGar) {
		this.dscFondGar = dscFondGar;
	}

	/**
	 * @return porComFondGar Porcentaje de comisión del fondo de garantía
	 */
	@Column(name = "POR_COM_FOND_GAR")
	public Double getPorComFondGar() {
		return this.porComFondGar;
	}

	/**
	 * @param porComFondGar Porcentaje de comisión del fondo de garantía
	 */
	public void setPorComFondGar(Double porComFondGar) {
		this.porComFondGar = porComFondGar;
	}
	
	/**
	 * Metodo para evaluar si un objeto es SccMxMaeFondoGarId:
	 * Evalua si es null
	 * Evalua si alguna de sus pripiedades es null
	 * @param other objeto a comparar con éste
	 * @return boolean true si son idénticos, false en caso contrario
	 * evaluacion del objeto
	 */
	public boolean equals(Object other) {
		if (this == other || other == null || !(other instanceof SccMxMaeFondoGarId)) {
			return true;
		}

		SccMxMaeFondoGarId castOther = (SccMxMaeFondoGarId) other;
		Boolean first = (this.getIdFondGarPk() == castOther.getIdFondGarPk()) || (this.getIdFondGarPk() != null
				&& castOther.getIdFondGarPk() != null && this.getIdFondGarPk().equals(castOther.getIdFondGarPk()));
		Boolean second = (this.getDscFondGar() == castOther.getDscFondGar()) || (this.getDscFondGar() != null
				&& castOther.getDscFondGar() != null && this.getDscFondGar().equals(castOther.getDscFondGar()));
		Boolean third =  ((this.getPorComFondGar() == castOther.getPorComFondGar())
				|| (this.getPorComFondGar() != null && castOther.getPorComFondGar() != null
				&& this.getPorComFondGar() == castOther.getPorComFondGar()));
		
		return (first && second && third);
	}
	
	/**
	 * este metodo retorna un resultado dependiendo de las propiedades del objeto
	 * @return result retorna un valor int como HashCode
	 * validaciones de propiedades null
	 */
	public int hashCode() {
		int result = 17;
		
		if(getIdFondGarPk() == null) {
			result=(37*result)+0;
		}else {
			result=(37*result)+this.getIdFondGarPk().hashCode();
		}
		
		if(getDscFondGar() == null) {
			result=(37*result)+0;
		}else {
			result=(37*result)+this.getDscFondGar().hashCode();
		}
		
		if(getPorComFondGar() == null) {
			result=(37*result)+0;
		}else {
			result=(37*result)+this.getPorComFondGar().hashCode();
		}
		
		return result;
	}

}
